import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import dotenv from 'dotenv';
const out='exports/mobile-ux-audit/regression';
await mkdir(out,{recursive:true});
const env=dotenv.parse(await readFile('.env.local'));
const ref=new URL(env.NEXT_PUBLIC_SUPABASE_URL).hostname.split('.')[0];
const base=process.env.MOBILE_TEST_URL || 'http://localhost:3112';
const browser=await chromium.launch({executablePath:'C:/Users/NERAJ/.cache/puppeteer/chrome/win64-146.0.7680.76/chrome-win64/chrome.exe',headless:true});
const user={id:'11111111-1111-4111-8111-111111111111',email:'audit@example.test'};
const session={access_token:'local-audit-only',refresh_token:'local-audit-only',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+86400,expires_in:86400,user};
const profile={user_id:user.id,name:'New Student',exam:'CAT',streak_count:0,daily_rc_streak:0,is_premium:true,birbal_credits:30,birbal_credit_month:'2026-9'};
const branding={brandName:'Auctor',logoUrl:'/logo.png',faviconUrl:'/icon-192.png',primaryColor:'#4f46e5',secondaryColor:'#0ea5e9',isInstitute:false};
const context={user,profile,tenant:{kind:'b2c'},branding,exam:'CAT',capabilities:{exam:'CAT',isCAT:true,showDailyRC:true,showCATSectionals:true},entitlement:{hasAccess:true,isPremium:true,isInstituteStudent:false},access:'allowed'};
const ctx=await browser.newContext({viewport:{width:390,height:844}});
await ctx.addInitScript(({ref,session})=>localStorage.setItem(`sb-${ref}-auth-token`,JSON.stringify(session)),{ref,session});
const calls=[],errors=[],results=[];
let workoutFail=false, speedFail=true, saveFail=true, rcFail=false, complete=false;
const challenge={id:'audit-rc',title:'Daily Reading Challenge',timer_minutes:8,source_year:'CAT 2023',difficulty:'Moderate',passage:'Reading requires distinguishing evidence from assumptions. '.repeat(70),questions:[1,2,3,4].map(i=>({id:i,question:`What does the passage suggest? (${i})`,options:['Evidence matters','All claims are true','Reading is unnecessary','Assumptions prove claims'],answer:'A',explanation:'Evidence supports conclusions.'}))};
await ctx.route('**/*',async route=>{
 const req=route.request(),u=new URL(req.url());
 const json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 if(u.pathname.startsWith('/api/')||u.pathname.startsWith('/rest/')||u.pathname.startsWith('/auth/'))calls.push({path:u.pathname,method:req.method()});
 if(u.pathname==='/api/product-tour')return json({completed:true});
 if(u.pathname==='/api/daily-status')return json({activities:[...(context.capabilities.showDailyRC?[{id:'daily_rc',name:'Daily RC Challenge',description:'One passage. Build your reading accuracy.',time:'8 min',available:true,completed:false,href:'/daily-challenge/instructions'}]:[]),{id:'workout',name:'Daily Workout',description:'Reading, vocabulary and speed in one guided session.',time:'25-30 min',available:true,completed:complete,href:'/?view=workout'},{id:'hangman',name:'Word Hunt',description:'A quick daily vocabulary puzzle.',time:'5 min',available:true,completed:false,href:'/?view=hangman'}],recent:null});
 if(u.pathname==='/api/tenant-context')return json({tenant:context.tenant,branding});
 if(u.pathname==='/api/session-context')return json(context);
 if(u.pathname==='/auth/v1/user')return json(user);
 if(u.pathname==='/auth/v1/token')return json(session);
 if(u.pathname.startsWith('/rest/v1/')){const table=u.pathname.split('/').at(-1);const single=req.headers().accept?.includes('object');if(table==='daily_hangman')return json(single?{id:'puzzle',max_lives:10,words:[{answer:'READ',hint:'Use text'}],passage:'Read carefully. Evidence matters.',level:'easy'}:[]);if(table==='daily_rc_attempts'&&req.method()==='POST')return saveFail?json({message:'Save unavailable'},503):json({id:'saved-rc'});if(table==='daily_rc_sets')return rcFail?json({message:'Unavailable'},503):json(challenge);if(table==='daily_rc_questions')return json(challenge.questions.map(q=>({...q,question_text:q.question,option_a:q.options[0],option_b:q.options[1],option_c:q.options[2],option_d:q.options[3],correct_answer:1})));return json(table==='profiles'?(single?profile:[profile]):(single?null:[]));}
 if(u.pathname==='/api/birbal-context')return json({analytics:{overallAccuracy:0,averageWPM:0,readingIQ:0,readerType:'New reader',skills:[],strongestSkill:'Not enough data',weakestSkill:'Not enough data'},recommendations:[]});
 if(u.pathname==='/api/birbal-coach')return json({coach:null});
 if(u.pathname==='/api/hangman-streak')return json({streak:0,isActiveToday:false});
 if(u.pathname==='/api/speed-generate')return speedFail?json({error:'Unavailable'},503):json({paragraphs:['Evidence helps readers think clearly.'],questions:[{question:'What helps?',options:['Evidence','Guessing'],correct:0}]});if(u.pathname==='/api/check-attempt')return json({attempted:complete,attempt:complete?{user_responses:{},total_score:4}:null});if(u.pathname==='/api/get-daily-workout'){if(workoutFail)return json({error:'Unavailable'},503);return json(Object.fromEntries(['speed','vocab','rc1','rc2','micro'].map(k=>[k,{passage:challenge.passage,questions:[{paragraph:'Evidence matters in reading.',question:'What matters?',options:['Evidence','Guessing','Ignoring','Nothing'],correctIndex:0,skill:'inference'}]}])));}if(u.pathname==='/api/get-daily-rc')return json({challenge});
 if(u.pathname==='/api/bootcamp')return json({calendar:{period:'UPCOMING',todayDay:null},attempt:null});
 if(u.pathname.startsWith('/api/'))return json({error:'Audit fixture: unavailable',items:[],messages:[],count:0},503);
 if(u.origin===base)return route.continue();
 return route.abort();
});
const page=await ctx.newPage();page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});let acceptDialog=true;page.on('dialog',d=>acceptDialog?d.accept():d.dismiss());page.setDefaultTimeout(12000);page.setDefaultNavigationTimeout(120000);
async function snap(name){
 await page.waitForTimeout(500);
 const data=await page.evaluate(()=>({url:location.pathname+location.search,width:innerWidth,height:innerHeight,scrollHeight:document.documentElement.scrollHeight,scrollWidth:document.documentElement.scrollWidth,scrollY,bodyScroll:document.body.scrollTop,bodyHeight:document.body.scrollHeight,scrollers:[...document.querySelectorAll('*')].filter(e=>e.scrollHeight>e.clientHeight+100&&['auto','scroll','hidden'].includes(getComputedStyle(e).overflowY)).map(e=>({tag:e.tagName,cls:e.className,top:e.scrollTop,h:e.clientHeight,total:e.scrollHeight})).slice(0,8),nav:[...document.querySelectorAll('nav')].filter(e=>e.getBoundingClientRect().height&&getComputedStyle(e).display!=='none').map(e=>e.innerText),headings:[...document.querySelectorAll('h1,h2,h3')].map(e=>({text:e.innerText,y:Math.round(e.getBoundingClientRect().top+scrollY)})),controls:[...document.querySelectorAll('button,a,input,select,textarea')].filter(e=>e.getBoundingClientRect().height).map(e=>{let r=e.getBoundingClientRect();return {text:(e.innerText||e.getAttribute('aria-label')||e.getAttribute('placeholder')||'').slice(0,90),x:Math.round(r.x),y:Math.round(r.y+scrollY),w:Math.round(r.width),h:Math.round(r.height)}}),text:document.body.innerText.slice(0,16000)}));
 results.push({name,...data});await page.screenshot({path:`${out}/${name}.png`,fullPage:false});await writeFile(`${out}/measurements.json`,JSON.stringify({results,errors,calls},null,2));console.log(name, data.scrollWidth,data.scrollHeight);
}
async function top(){await page.evaluate(()=>{document.body.scrollTop=0;document.documentElement.scrollTop=0;document.querySelectorAll('main').forEach(e=>e.scrollTop=0)});}
async function widths(name){for(const width of [320,360,375,390,414]){await page.setViewportSize({width,height:844});await top();await snap(name+'-'+width);}}

const sizes=[[320,568],[320,844],[360,844],[375,844],[390,844],[414,844],[768,844],[800,844],[899,844],[900,844],[1024,844],[1440,900]];
async function go(path){await page.goto(base+path,{waitUntil:'domcontentloaded'});await page.waitForTimeout(700);}
async function fits(){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No page overflow '+page.url());}
async function visible(locator){await locator.waitFor({state:'visible'});}
try{
 await go('/');await visible(page.locator('.mobile-primary').first());
 for(const [width,height] of (process.env.MOBILE_SKIP_MATRIX?[[320,568]]:sizes)){await page.setViewportSize({width,height});await page.waitForTimeout(150);await fits();if(width<900){const nav=page.locator('.auctor-mobile-nav');assert.equal(await nav.locator('a').count(),4);assert.deepEqual(await nav.locator('a').allTextContents(),['Home','Today','Practice','Profile']);const box=await page.locator('.daily-focus .mobile-primary').first().boundingBox();assert.ok(box&&box.y+box.height<height-64,'Home CTA above fold');assert.equal(await nav.locator('[aria-current=page]').getAttribute('aria-label'),'Home');}else assert.equal(await page.locator('aside').first().isVisible(),true);assert.equal(await page.getByText('Boot Camp',{exact:true}).count(),0);await snap('home-'+width+'x'+height);}
 await page.setViewportSize({width:320,height:568});
 await page.getByRole('link',{name:'Today',exact:true}).click();await visible(page.getByRole('tab',{name:'Workout',exact:true}));await page.getByRole('tab',{name:'Workout',exact:true}).click();await page.waitForURL(/activity=workout/);await page.reload({waitUntil:'domcontentloaded'});await visible(page.getByRole('link',{name:/Start Workout/}));
 await page.getByRole('link',{name:'Practice',exact:true}).click();await visible(page.getByRole('heading',{name:'Practice',exact:true}));assert.equal(await page.getByText('Grammar',{exact:true}).count(),0);await fits();await page.getByRole('tab',{name:'Verbal & Speed',exact:true}).click();await page.getByRole('button',{name:/Vocabulary Lab/}).click();await visible(page.locator('.generic-tab-select select').first());await page.locator('.generic-tab-select select').first().selectOption('profile');await page.waitForURL(/tab=profile/);await page.reload({waitUntil:'domcontentloaded'});await visible(page.locator('.generic-tab-select select').first());assert.equal(await page.locator('.generic-tab-select select').first().inputValue(),'profile');
 await go('/?view=mentor');await visible(page.getByRole('textbox',{name:'Message Birbal'}));await page.getByRole('textbox',{name:'Message Birbal'}).fill('How do I read better?');const send=page.getByRole('button',{name:'Send message'});assert.equal(await page.locator('.birbal-launcher').count(),0);assert.ok(await send.evaluate(e=>{const r=e.getBoundingClientRect();return r.right<=innerWidth&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}));await page.setViewportSize({width:320,height:340});await page.waitForTimeout(500);assert.ok(await send.evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));await snap('chat-keyboard-sized');await page.setViewportSize({width:320,height:568});await send.click();await visible(page.locator('.mobile-conversation [role=alert]'));assert.equal(await page.getByRole('textbox',{name:'Message Birbal'}).inputValue(),'How do I read better?');await page.getByRole('button',{name:'Close Birbal conversation'}).click();await visible(page.locator('.daily-focus').first());
 workoutFail=true;await go('/?view=workout');await visible(page.getByRole('button',{name:'Retry',exact:true}));workoutFail=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await visible(page.getByRole('button',{name:/Start Workout/}));assert.equal(await page.locator('.workout-activity-card').count(),4);await page.getByRole('button',{name:/Start Workout/}).scrollIntoViewIfNeeded();await page.getByRole('button',{name:/Start Workout/}).click();await visible(page.getByRole('button',{name:'Exit activity'}));assert.equal(await page.locator('.auctor-mobile-nav').count(),0);acceptDialog=false;await page.getByRole('button',{name:'Exit activity'}).click();assert.match(page.url(),/view=workout/);acceptDialog=true;await page.getByRole('button',{name:'Exit activity'}).click();await visible(page.getByRole('heading',{name:'Today',exact:true}));
 await go('/?view=speed');await page.getByRole('button',{name:/Start Drill/}).click();await visible(page.getByRole('button',{name:'Retry',exact:true}));speedFail=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await visible(page.getByRole('button',{name:'Exit activity'}));await page.getByRole('button',{name:'Exit activity'}).click();
 rcFail=true;await go('/daily-challenge/test');await visible(page.getByRole('button',{name:'Retry',exact:true}));rcFail=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await visible(page.getByRole('tab',{name:/Questions/}));await page.getByRole('tab',{name:/Questions/}).click();for(const [width,height] of sizes){await page.setViewportSize({width,height});await fits();await snap('daily-questions-'+width+'x'+height);}
 await page.setViewportSize({width:320,height:568});await page.getByRole('button',{name:/A Evidence matters/}).click();await page.getByRole('button',{name:'Submit Answers',exact:true}).first().click();await visible(page.getByRole('button',{name:'Retry',exact:true}));assert.equal(await page.getByRole('button',{name:/A Evidence matters/}).getAttribute('aria-pressed'),'true');await snap('daily-save-recovery');await page.getByRole('button',{name:'Exit activity'}).click();
 await go('/arena/result/missing');await visible(page.getByRole('button',{name:'Retry',exact:true}));
 context.entitlement.hasAccess=false;context.entitlement.isPremium=false;await go('/?view=practice');await page.getByRole('tab',{name:'Verbal & Speed',exact:true}).click();await page.getByRole('button',{name:/Vocabulary Lab/}).click();await visible(page.getByRole('dialog'));await page.getByRole('link',{name:'Try free daily practice'}).click();await visible(page.getByRole('heading',{name:'Today',exact:true}));
 context.capabilities.showDailyRC=false;context.capabilities.showCATSectionals=false;context.capabilities.isCAT=false;context.exam='IPMAT';await go('/?view=today');await visible(page.getByRole('tab',{name:'Workout',exact:true}));assert.equal(await page.getByRole('tab',{name:'Daily RC',exact:true}).count(),0);
 complete=true;await go('/?view=today&activity=workout');await visible(page.getByRole('link',{name:/Review Workout/}));await snap('completed-workout');
 assert.deepEqual(errors,[]);console.log('PASS: viewport, navigation, locks, eligibility, completion, chat, recovery and assessment journeys');
}finally{await writeFile(out+'/measurements.json',JSON.stringify({results,errors,calls},null,2));await browser.close();}


