'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts'
import { bootcampRequest } from '@/lib/bootcamp/client'
import BootCampShell from './BootCampShell'
import s from './overall.module.css'
const pct=n=>n==null?'—':`${Number(n.toFixed(1))}%`
const seconds=n=>n==null?'—':`${Math.round(n)}s`
function Empty({children}) {return <div className={s.empty}>{children || 'Your training profile is taking shape. Complete 2–3 more training days to build your evidence.'}</div>}
function Trend({data,series,timing=false}) {
  if(!data.some(row=>series.some(item=>row[item.key]!=null)))return <Empty>{timing?'No positive question-view timing recorded yet. Timing appears only when observations are available.':undefined}</Empty>
  return <div className={s.chart} tabIndex={0} aria-label={timing?'Recorded question-view time by training day':'Accuracy by training day'}><ResponsiveContainer width="100%" height={280}><LineChart data={data} margin={{top:15,right:20,bottom:10,left:0}} accessibilityLayer><CartesianGrid stroke="#233746" strokeDasharray="3 6" vertical={false}/><XAxis dataKey="day" type="number" domain={['dataMin','dataMax']} allowDecimals={false} tickFormatter={n=>`D${n}`} stroke="#91a9bb"/><YAxis domain={timing?[0,'auto']:[0,100]} unit={timing?'s':'%'} width={48} stroke="#91a9bb"/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className={s.tooltip}><strong>Day {label}</strong>{payload.map(p=><div key={p.dataKey} style={{color:p.color}}>{p.name}: {timing?seconds(p.value):pct(p.value)} · n={p.payload[`${p.dataKey}Count`] ?? p.payload.attempted}</div>)}</div>:null}/><Legend/>{series.map(item=><Line key={item.key} dataKey={item.key} name={item.name} stroke={item.color} strokeWidth={2.5} dot={{r:4}} activeDot={{r:6}} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>
}
function Profiles({items}) {const visible=items.filter(p=>p.sufficient);return <>{visible.length?<div className={s.bars}>{visible.map(p=><div className={s.bar} key={p.name}><div><strong>{p.name}</strong><small>n = {p.attempted} · {p.days} days</small></div><div className={s.track}><span style={{width:`${p.accuracy}%`}}/></div><b>{pct(p.accuracy)} <small title={p.trend.interpretation}>{p.trend.sufficientEvidence?({improving:'↑',declining:'↓',stable:'→'})[p.trend.direction]:''}</small></b></div>)}</div>:<Empty/>}{items.some(p=>!p.sufficient)&&<p className={s.note}>{items.filter(p=>!p.sufficient).length} categories need more observations before comparison.</p>}</>}
function Panel({title,kicker,children}) {return <section className={s.panel}><p className={s.eyebrow}>{kicker}</p><h2>{title}</h2>{children}</section>}
export default function BootCampOverallAnalytics() {
  const [data,setData]=useState(null),[error,setError]=useState(null),[tab,setTab]=useState('Overview'),[reload,setReload]=useState(0)
  useEffect(()=>{let live=true;setError(null);bootcampRequest('/analytics').then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e)});return()=>{live=false}},[reload])
  const trend=data?.accuracyByDay.map(d=>({day:d.day,accuracy:d.accuracy,attempted:d.attempted,rc:d.rc.accuracy,va:d.va.accuracy,rcCount:d.rc.attempted,vaCount:d.va.attempted,rcTime:d.rc.averageSeconds,vaTime:d.va.averageSeconds,rcTimeCount:d.rc.observed,vaTimeCount:d.va.observed}))||[]
  return <BootCampShell><div className={s.page}><Link className={s.back} href="/boot-camp">← Training calendar</Link><header className={s.heading}><p className={s.eyebrow}>Your VARC training intelligence</p><h1>See your training take shape.</h1><p>Every saved result. A clearer view of what comes next.</p></header>
    {error?<div role="alert" className={s.empty}><p>{error.message}</p>{error.status===401?<Link href="/login">Sign in</Link>:error.status===402?<Link href="/pricing">View plans</Link>:<button onClick={()=>setReload(n=>n+1)}>Try again</button>}</div>:!data?<p role="status">Reading your saved training…</p>:<>
    <section className={s.hero} aria-label="Training snapshot"><div className={s.ring} style={{'--progress':`${data.curriculumPercent}%`}}><div><strong>{data.daysCompleted}<small> / 50</small></strong><span>days completed</span></div></div><div className={s.heroCopy}><p className={s.eyebrow}>Boot Camp progress</p><h2>{data.curriculumPercent}% of your curriculum</h2><p>{data.calendar.todayDay?`Calendar: Day ${data.calendar.todayDay} of 50`:'Your 50-day training journey'} · {data.daysStarted} days started</p><div className={s.metrics}>{[['Questions attempted',data.questionsAttempted],['Accuracy',pct(data.accuracy)],['Current streak',`${data.currentStreak}d`],['Best streak',`${data.bestStreak}d`]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section>
    <nav className={s.tabs} aria-label="Analytics sections">{['Overview','Performance','Skills','Consistency'].map(name=><button key={name} aria-current={tab===name?'page':undefined} onClick={()=>setTab(name)}>{name}</button>)}</nav>
    {tab==='Overview'&&<div className={s.grid}><Panel title="Your accuracy trajectory" kicker="Completed training days"><Trend data={trend} series={[{key:'accuracy',name:'Accuracy',color:'#87e4e3'}]}/><p className={s.note}>Actual completed days only; missing days have no data point. {data.daysCompleted<4?'A few more completed days will help establish a direction.':'Compare sample sizes before interpreting a change.'}</p></Panel><Panel title="What your training is showing" kicker="Birbal’s read"><p className={s.read}>{data.birbal.observation}</p><h3>What’s improving</h3>{data.birbal.improving.length?data.birbal.improving.map(x=><p key={x}>{x}</p>):<p className={s.note}>Not enough evidence of a direction yet.</p>}<h3>Watch this</h3>{data.birbal.watch.length?data.birbal.watch.map(x=><p key={x}>{x}</p>):<p className={s.note}>Keep building observations; no weakness needs to be invented.</p>}<h3>Next focus</h3><p>{data.birbal.focus}</p></Panel></div>}
    {tab==='Performance'&&<><div className={s.grid}><Panel title="RC and VA, side by side" kicker="Accuracy across days"><Trend data={trend} series={[{key:'rc',name:'RC',color:'#87e4e3'},{key:'va',name:'VA',color:'#c8a9ed'}]}/><p className={s.note}>Warm-up is separate. RC {pct(data.rc.accuracy)} · VA {pct(data.va.accuracy)} · warm-up {pct(data.warmup.accuracy)}.</p></Panel><Panel title="Time with each question" kicker="Observed active view"><div className={s.metrics}><div><strong>{seconds(data.rc.averageSeconds)}</strong><span>RC · {data.rc.observed}/{data.rc.attempted} observed</span></div><div><strong>{seconds(data.va.averageSeconds)}</strong><span>VA · {data.va.observed}/{data.va.attempted} observed</span></div></div><Trend data={trend} timing series={[{key:'rcTime',name:'RC view time',color:'#87e4e3'},{key:'vaTime',name:'VA view time',color:'#c8a9ed'}]}/><p className={s.note}>{data.rules.timing}</p></Panel></div><Panel title="Performance by question type" kicker="Evidence, with sample sizes"><Profiles items={data.accuracyByQuestionType}/></Panel></>}
    {tab==='Skills'&&<Panel title="Your developing skill profile" kicker="Approved curriculum metadata"><Profiles items={data.accuracyBySkill}/><p className={s.note}>{data.rules.samples}</p><p className={s.note}>These are observations on different authored questions, not fixed diagnoses of ability.</p></Panel>}
    {tab==='Consistency'&&<div className={s.grid}><Panel title="Showing up for training" kicker="Actual calendar activity"><div className={s.heatmap}>{data.consistency.map(d=><div key={d.day} tabIndex={0} className={s[d.status]} title={`${d.date}: ${d.status.replaceAll('_',' ')}. Curriculum Day ${d.day}: ${d.curriculumStatus.replaceAll('_',' ')}`} aria-label={`${d.date}: ${d.status.replaceAll('_',' ')}; curriculum Day ${d.day}: ${d.curriculumStatus.replaceAll('_',' ')}`}><small>{d.date.slice(5)}</small><b>{d.status==='completed'?'✓':d.status==='partial'?'•':d.status==='future'?'·':'–'}</b></div>)}</div><p className={s.note}>✓ Completed activity · • Partial activity · – No recorded activity · faded: future</p><p className={s.note}>{data.rules.consistency}</p><details><summary>Recorded activity dates</summary>{data.activityDates.length?data.activityDates.map(d=><p key={d.date}>{d.date} / {d.status}</p>):<p className={s.note}>No saved activity yet.</p>}</details></Panel><Panel title="Your curriculum, covered" kicker="Progress through 50 days">{[['Training days completed',data.daysCompleted,50],['Questions attempted',data.questionsAttempted,data.curriculum.availableQuestions]].map(([label,value,total])=><div className={s.progress} key={label}><p>{label}<strong>{value} / {total}</strong></p><progress value={value} max={total||1}/></div>)}<p className={s.note}>Question denominator: published, released curriculum plus saved attempt snapshots.</p><div className={s.metrics}>{[['RC passages',data.curriculum.rcPassages],['VA answers',data.curriculum.vaQuestions],['Warm-ups',data.curriculum.warmups]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label} completed</span></div>)}</div><h3>Work in progress</h3>{data.partialDays.length?data.partialDays.map(d=><p key={d.day}><Link href={`/boot-camp/day/${d.day}`}>Resume Day {d.day} →</Link> · {d.savedAnswers} saved answers</p>):<p className={s.note}>No partial training days.</p>}</Panel></div>}
    <p className={s.note}>{data.rules.performance}</p></>}
  </div></BootCampShell>
}
