'use client'
import s from './report.module.css'
const pct=n=>n===null?'No attempts':`${Number(n.toFixed(1))}%`
const time=n=>`${Math.floor(n/60)}m ${Math.round(n%60)}s`
const outcomes=[['correct','Correct','#99cdb0'],['incorrect','Incorrect','#d79c87'],['skipped','Skipped','#bfa879'],['not_reached','Not reached','#70889c'],['timed_out','Timed out','#9c91ba']]
function Bars({rows,label,maximum=100,timing=false}) {return <div className={s.bars} role="img" aria-label={label}>{rows.map(row=><div className={s.barRow} key={row.label}><div><span>{row.label}</span><small>{row.detail}</small></div><div className={s.track}><span style={{width:`${Math.max(0,Math.min(100,(row.value || 0)/maximum*100))}%`}}/></div><strong>{timing?time(row.value):pct(row.value)}</strong></div>)}</div>}
function Ring({value,label,children}) {return <div className={s.ring} role="img" aria-label={label}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52" fill="none" stroke="#203644" strokeWidth="7"/><circle cx="60" cy="60" r="52" fill="none" stroke="#86dfed" strokeWidth="7" pathLength="100" strokeDasharray={`${value || 0} 100`} transform="rotate(-90 60 60)" strokeLinecap="round"/></svg><div>{children}</div></div>}
export default function BootCampReportAnalytics({report:r,dayNumber=1}) {
  const attempted=r.blocks.filter(b=>b.answered),high=attempted.length?Math.max(...attempted.map(b=>b.accuracy)):null,low=attempted.length?Math.min(...attempted.map(b=>b.accuracy)):null
  let offset=0
  return <div className={s.analytics}>
    <section className={s.analyticsHero}><p className={s.eyebrow}>Day {String(dayNumber).padStart(2,'0')} performance</p><div className={s.heroVisual}><Ring value={r.answered?r.accuracy:0} label={`Overall accuracy: ${pct(r.answered?r.accuracy:null)}`}><strong>{r.answered?pct(r.accuracy):'—'}</strong><span>Accuracy</span></Ring><div><h2>{r.answered}<small> / {r.total} attempted</small></h2><p><b>{r.correct}</b> correct<br/><b>{r.incorrect}</b> incorrect</p><small>Accuracy = correct ÷ attempted</small></div></div></section>
    <section className={s.chart}><p className={s.eyebrow}>Where did your answers land?</p><h2>Block performance</h2><Bars label="Block accuracy chart" rows={r.blocks.map(b=>({label:b.label,value:b.answered?b.accuracy:null,detail:`${b.correct}/${b.answered} attempted correct · ${b.total} questions`}))}/></section>
    <section className={s.chart}><p className={s.eyebrow}>The reasoning behind the result</p><h2>Question-type performance</h2><p className={s.note}>Small samples describe today, not a stable skill level.</p><Bars label="Question type accuracy chart" rows={r.questionTypes.map(q=>({label:q.type,value:q.accuracy,detail:`${q.correct}/${q.attempted} attempted correct`}))}/></section>
    <div className={s.chartStack}><section className={s.chart}><p className={s.eyebrow}>Every question accounted for</p><h2>Outcome distribution</h2><div className={s.outcomes}><div className={s.ring} role="img" aria-label={outcomes.map(([key,label])=>`${label}: ${r[key]}`).join(', ')}><svg viewBox="0 0 120 120" aria-hidden="true">{outcomes.map(([key,,color])=>{const length=r.total?r[key]/r.total*100:0,start=offset;offset+=length;return <circle key={key} cx="60" cy="60" r="50" fill="none" stroke={color} strokeWidth="12" pathLength="100" strokeDasharray={`${length} ${100-length}`} strokeDashoffset={-start} transform="rotate(-90 60 60)"/>})}</svg><div><strong>{r.total}</strong><span>Questions</span></div></div><ul>{outcomes.map(([key,label,color])=><li key={key}><i style={{background:color}}/><span>{label}</span><strong>{r[key]}</strong></li>)}</ul></div></section>
    <section className={s.chart}><p className={s.eyebrow}>Time in training</p><h2>{time(r.elapsed_seconds)} <small>activity time</small></h2><Bars label="Block elapsed activity time chart" timing maximum={Math.max(1,...r.blocks.map(b=>b.elapsed_seconds))} rows={r.blocks.map(b=>({label:b.label,value:b.elapsed_seconds}))}/><p className={s.note}>Elapsed block time can include time away; review and coaching are excluded. This is not wall-clock session time.</p><p className={s.note}>{r.timing.averageSeconds===null?'No positive question-view timing recorded.':`${Math.round(r.timing.averageSeconds)}s average recorded question view · ${r.timing.observed}/${r.timing.total} measured.`} Approximate active-view time is not reading speed.</p></section></div>
    <section className={s.dataSummary}><p className={s.eyebrow}>What the data says</p><h2>Today’s evidence. Tomorrow’s starting point.</h2><p>{high===null?'No attempted answers were recorded, so block accuracy cannot be compared.':high===low?`All attempted blocks finished at ${pct(high)} accuracy today.`:`Highest block accuracy: ${attempted.filter(b=>b.accuracy===high).map(b=>b.label).join(', ')} (${pct(high)}). Lowest: ${attempted.filter(b=>b.accuracy===low).map(b=>b.label).join(', ')} (${pct(low)}). Compare the question counts before drawing conclusions.`}</p><p>{r.debrief.watch}</p></section>
    <details className={`${s.details} ${s.dataTables}`}><summary>Explore the detailed data</summary><div className={s.tableWrap} tabIndex={0} role="region" aria-label="Detailed block results"><table><caption>Block performance</caption><thead><tr>{['Block','Attempted / total','Correct','Incorrect','Skipped','Not reached','Timed out','Accuracy','Time'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{r.blocks.map(b=><tr key={b.key}><th scope="row">{b.label}</th><td>{b.answered}/{b.total}</td><td>{b.correct}</td><td>{b.incorrect}</td><td>{b.skipped}</td><td>{b.not_reached}</td><td>{b.timed_out}</td><td>{pct(b.answered?b.accuracy:null)}</td><td>{time(b.elapsed_seconds)}</td></tr>)}</tbody></table></div><div className={s.tableWrap} tabIndex={0} role="region" aria-label="Detailed question type results"><table><caption>Question-type performance</caption><thead><tr><th>Type</th><th>Attempted / total</th><th>Correct</th><th>Accuracy</th></tr></thead><tbody>{r.questionTypes.map(q=><tr key={q.type}><th scope="row">{q.type}</th><td>{q.attempted}/{q.total}</td><td>{q.correct}</td><td>{pct(q.accuracy)}</td></tr>)}</tbody></table></div>{r.timing.fastest && <p className={s.note}>Shortest recorded question view: {r.timing.fastest.block.toUpperCase()} Q{r.timing.fastest.number}, {Math.round(r.timing.fastest.seconds)}s. Longest: {r.timing.slowest.block.toUpperCase()} Q{r.timing.slowest.number}, {Math.round(r.timing.slowest.seconds)}s. These are view durations, not skill rankings.</p>}</details>
  </div>
}
