import { GRAMMAR_ONTOLOGY, GRAMMAR_QUESTION_TYPES, GRAMMAR_TRAP_TYPES } from "../lib/grammarOntology.js"

const c = (id, skill, trap, focus) => ({ id, skill, trap, focus })
const topic = ({ name, description, controlledSites, forbidden, distractors, questionTypes, easy, moderate, hard, productionReady = false }) => ({ name, description, controlledSites, forbidden, distractors, questionTypes, productionReady, difficulties: { easy, moderate, hard } })

export const GRAMMAR_TOPIC_BLUEPRINTS = {
  "subject-verb-agreement": topic({ name: "Subject–Verb Agreement", description: "Agreement controllers and structurally competing number cues.", controlledSites: ["agreement head", "finite verb form", "number interpretation"], forbidden: ["dialect-only collective agreement", "surface number matching", "ambiguous relative antecedents"], distractors: "Use proximity attraction, false compounds, and competing controller cues.", questionTypes: ["Sentence Correction", "Error Detection", "Best Revision", "Fill in the Blank"], productionReady: true,
    easy: [c("intervening-head", "Intervening Phrase Attraction", "Proximity Attraction", "Head subject separated from its verb"), c("correlative-nearer", "Either-Or and Neither-Nor", "Proximity Attraction", "Nearer correlative subject"), c("compound-controller", "Compound Subjects", "Number Confusion", "True compound subject"), c("plural-looking-singular", "Titles and Amounts", "Surface Agreement", "Singular title or name ending in -s"), c("unit-quantity", "Titles and Amounts", "Meaning-Grammar Conflict", "Quantity interpreted as one unit")],
    moderate: [c("one-of-relative", "Relative Clause Agreement", "Proximity Attraction", "Plural antecedent inside one-of relative"), c("collective-unified", "Collective Noun Agreement", "Meaning-Grammar Conflict", "Contextually unified collective"), c("number-quantifier", "Basic Number Agreement", "Number Confusion", "A number versus the number"), c("additive-controller", "Intervening Phrase Attraction", "Proximity Attraction", "Additive phrase versus compound"), c("inverted-controller", "Inverted Structures", "Proximity Attraction", "Post-verbal subject in inversion")],
    hard: [c("relative-controller-contrast", "Relative Clause Agreement", "Rule Collision", "One-of and only-one relative contrast"), c("number-relative-additive", "Relative Clause Agreement", "Proximity Attraction", "Number quantifier plus relative and additive sites"), c("correlative-embedded", "Either-Or and Neither-Nor", "Rule Collision", "Correlative controller plus independent embedded site"), c("quantity-number-contrast", "Titles and Amounts", "Meaning-Grammar Conflict", "Unit quantity plus a-number plural"), c("title-relative-interaction", "Titles and Amounts", "Surface Agreement", "Plural-looking title plus independent relative site")]}),

  pronouns: topic({ name: "Pronouns", description: "Pronoun form, reference, case, binding, and discourse consistency.", controlledSites: ["pronoun form", "antecedent/reference", "syntactic case or binding domain"], forbidden: ["arbitrary gender assumptions", "dialect-dependent collective reference", "unresolved antecedent ambiguity", "disputed informal case preference"], distractors: "Use plausible wrong antecedents, surface case attraction, and binding-domain errors.", questionTypes: ["Sentence Correction", "Fill in the Blank", "Best Revision", "Contextual Usage"], productionReady: true,
    easy: [c("antecedent-agreement", "Pronoun-Antecedent Agreement", "Number Confusion", "Fixed-number antecedent"), c("basic-case", "Pronoun Case", "Wrong Word Form", "Clear subject or object role"), c("local-reflexive", "Reflexive Pronouns", "Misleading Familiarity", "Local co-reference"), c("demonstrative-number", "Demonstrative Pronouns", "Number Confusion", "Demonstrative and explicit referent"), c("indefinite-reference", "Indefinite Pronouns", "Pronoun Reference Confusion", "Indefinite pronoun with defensible form")],
    moderate: [c("coordinated-case", "Pronoun Case", "Surface Agreement", "Case inside coordination"), c("reference-repair", "Reference Clarity", "Pronoun Reference Confusion", "Meaning-preserving ambiguity repair"), c("relative-role", "Relative Pronouns", "Wrong Word Form", "Role inside relative clause"), c("embedded-reflexive", "Reflexive Pronouns", "Modifier Attachment", "Local subject across embedded clause"), c("viewpoint-consistency", "Pronoun Consistency", "Partial Correction", "Person or number shift")],
    hard: [c("case-embedded", "Pronoun Case", "Rule Collision", "Coordination plus independent embedded case"), c("relative-reference", "Relative Pronouns", "Pronoun Reference Confusion", "Relative role plus unique antecedent"), c("agreement-reflexive", "Pronoun-Antecedent Agreement", "Rule Collision", "Agreement plus independent binding decision"), c("reference-consistency", "Reference Clarity", "Partial Correction", "Cross-clause reference plus viewpoint consistency"), c("dummy-demonstrative", "Dummy Pronouns", "Contextual Fit Trap", "Dummy function plus referential demonstrative")]}),

  "parts-of-speech": topic({ name: "Parts of Speech", description: "Word-class decisions based on syntactic function rather than spelling.", controlledSites: ["target word", "phrase position", "syntactic function and word class"], forbidden: ["definition-only recall", "classification without sentence context", "labels determined solely by suffix"], distractors: "Use neighboring plausible classes and form-versus-function confusion.", questionTypes: ["Contextual Usage", "Correct Sentence", "Fill in the Blank", "Best Revision"],
    easy: [c("noun-verb-context", "Contextual Word Class", "Contextual Fit Trap", "Same form used as noun or verb"), c("adjective-adverb-function", "Word Class Identification", "Wrong Word Form", "Modifier target distinguishes adjective/adverb"), c("pronoun-determiner-role", "Form vs Function", "Surface Agreement", "Determiner versus stand-alone pronoun"), c("preposition-conjunction-role", "Word Class Identification", "Misleading Familiarity", "Complement type distinguishes class"), c("phrase-head-function", "Phrase-Level Function", "Contextual Fit Trap", "Identify phrase function in a clause")],
    moderate: [c("functional-shift", "Functional Shift", "Misleading Familiarity", "Lexical item shifted to a new class"), c("participle-adjective", "Form vs Function", "Wrong Word Form", "Participle versus adjectival use"), c("gerund-noun-verb", "Ambiguous Word Class", "Contextual Fit Trap", "-ing form classified by structure"), c("that-multiple-functions", "Contextual Word Class", "Pronoun Reference Confusion", "That as determiner, pronoun, or conjunction"), c("phrase-clause-function", "Phrase-Level Function", "Modifier Attachment", "Whole constituent classified by clause role")],
    hard: [c("multiuse-lexeme", "Functional Shift", "Rule Collision", "One lexeme with distinct classes across clauses"), c("infinitival-function", "Phrase-Level Function", "Contextual Fit Trap", "Infinitival phrase function plus local word class"), c("embedded-classification", "Ambiguous Word Class", "Modifier Attachment", "Class determined inside embedded structure"), c("conversion-scope", "Form vs Function", "Semantic Plausibility Trap", "Conversion plus scope-sensitive meaning"), c("parallel-class-contrast", "Contextual Word Class", "False Parallelism", "Superficially parallel words serving different functions")]}),

  nouns: topic({ name: "Nouns", description: "Countability, number, possession, formation, and contextual noun behavior.", controlledSites: ["noun form", "countability/number", "possessive or quantifier relation"], forbidden: ["regional plural variants", "mass/count readings without context", "possessive punctuation ambiguity"], distractors: "Use countability transfer, irregular-plural analogy, and possessive-scope errors.", questionTypes: ["Sentence Correction", "Fill in the Blank", "Error Detection", "Correct Sentence"], productionReady: true,
    easy: [c("count-mass-choice", "Countability", "Countability Confusion", "Clear count versus mass use"), c("irregular-plural", "Irregular Plurals", "Overgeneralized Rule", "Productive versus irregular plural"), c("compound-plural-head", "Compound Nouns", "Wrong Word Form", "Pluralize compound head"), c("basic-possessive", "Possessive Forms", "Surface Agreement", "Singular versus plural possessive"), c("noun-formation", "Noun Formation", "Wrong Word Form", "Noun derivative required by syntax")],
    moderate: [c("contextual-countability", "Contextual Noun Usage", "Contextual Fit Trap", "Same noun with count and mass readings"), c("quantifier-countability", "Quantifier-Noun Compatibility", "Countability Confusion", "Quantifier controls noun form"), c("collective-meaning", "Collective Nouns", "Meaning-Grammar Conflict", "Unit versus members made explicit"), c("compound-possessive-scope", "Possessive Forms", "Modifier Attachment", "Joint versus separate possession"), c("number-agreement-noun", "Noun Number and Agreement", "Number Confusion", "Noun number propagated to dependent form")],
    hard: [c("countability-quantifier-reference", "Countability", "Rule Collision", "Two linked sites using the same flexible noun in an explicitly signalled mass reading and an explicitly signalled count reading; require a compatible quantifier at one site and number/reference reasoning at the other, with neither site removable"), c("compound-number-possession", "Compound Nouns", "Partial Correction", "Compound plural plus possessive scope"), c("formation-context", "Noun Formation", "Contextual Fit Trap", "Competing derivatives with distinct meanings"), c("collective-number-chain", "Collective Nouns", "Meaning-Grammar Conflict", "Collective interpretation across noun/pronoun sites"), c("multiple-noun-constraints", "Contextual Noun Usage", "Rule Collision", "Two nouns requiring different count/number decisions")]}),

  adjectives: topic({ name: "Adjectives", description: "Adjective form, order, position, complementation, and gradability.", controlledSites: ["adjective form", "modified head", "position/order/complement"], forbidden: ["order based only on personal style", "nonstandard gradability without context", "participial meaning left vague"], distractors: "Use adjective/adverb confusion, participial role reversal, and order-category swaps.", questionTypes: ["Sentence Correction", "Fill in the Blank", "Correct Sentence", "Best Revision"],
    easy: [c("identify-modifier", "Adjective Identification", "Wrong Word Form", "Adjective modifying noun or complement"), c("basic-order", "Adjective Order", "Misleading Familiarity", "Canonical category order"), c("participial-meaning", "Participial Adjectives", "Meaning-Grammar Conflict", "Causing versus experiencing adjective"), c("attributive-predicative", "Predicative vs Attributive Use", "Contextual Fit Trap", "Position licensed by adjective"), c("compound-hyphenation", "Compound Adjectives", "Surface Agreement", "Pre-nominal compound form")],
    moderate: [c("multi-category-order", "Adjective Order", "Rule Collision", "Three adjective categories with natural order"), c("gradable-intensifier", "Gradability", "Contextual Fit Trap", "Degree word compatible with adjective"), c("adjective-complement", "Adjective Complements", "Idiomatic Usage Trap", "Licensed preposition or clause complement"), c("participle-attachment", "Participial Adjectives", "Modifier Attachment", "Participial adjective and intended noun"), c("formation-meaning", "Adjective Formation", "Wrong Word Form", "Derivative selected by contextual meaning")],
    hard: [c("order-scope", "Adjective Order", "Modifier Attachment", "Order changes scope or classification"), c("gradability-complement", "Gradability", "Rule Collision", "Degree plus complement licensing"), c("position-meaning", "Predicative vs Attributive Use", "Meaning-Grammar Conflict", "Position-sensitive adjective meaning"), c("participial-compound", "Compound Adjectives", "Partial Correction", "Participial meaning plus compound structure"), c("multi-adjective-revision", "Adjective Complements", "Rule Collision", "Order, form, and complement interaction")]}),

  adverbs: topic({ name: "Adverbs", description: "Adverb form, placement, scope, focus, frequency, and sentence meaning.", controlledSites: ["adverb form", "modified constituent", "position and scope"], forbidden: ["placement variants with no meaning difference", "style-only sentence-adverb disputes", "ambiguous scope"], distractors: "Use adjective forms, misplaced scope, and frequency-position attraction.", questionTypes: ["Sentence Correction", "Fill in the Blank", "Best Revision", "Contextual Usage"],
    easy: [c("adjective-adverb", "Adjective vs Adverb", "Wrong Word Form", "Verb versus noun modifier"), c("manner-position", "Adverb Position", "Modifier Attachment", "Clear manner-adverb placement"), c("frequency-position", "Frequency Adverbs", "Misleading Familiarity", "Frequency with lexical or auxiliary verb"), c("degree-choice", "Degree Adverbs", "Contextual Fit Trap", "Degree adverb compatible with adjective"), c("identify-adverb", "Adverb Identification", "Surface Agreement", "Identify function in context")],
    moderate: [c("focus-placement", "Focusing Adverbs", "Modifier Attachment", "Only/even focus target"), c("sentence-adverb", "Sentence Adverbs", "Contextual Fit Trap", "Clause stance versus manner"), c("position-meaning", "Meaning Change by Position", "Meaning-Grammar Conflict", "Placement changes interpretation"), c("auxiliary-adverb-order", "Adverb Position", "Rule Collision", "Adverb within multiword verb phrase"), c("degree-gradability", "Degree Adverbs", "Semantic Plausibility Trap", "Intensifier and gradability")],
    hard: [c("focus-scope-revision", "Focusing Adverbs", "Modifier Attachment", "Focus placement plus meaning preservation"), c("multi-adverb-order", "Adverb Position", "Rule Collision", "Frequency, manner, and sentence adverbs"), c("sentence-manner-contrast", "Sentence Adverbs", "Meaning-Grammar Conflict", "Same form with clause versus manner scope"), c("negative-adverb-inversion", "Meaning Change by Position", "Rule Collision", "Fronted negative adverb and inversion"), c("scope-parallel-clauses", "Meaning Change by Position", "False Parallelism", "Different adverb scopes across coordinated clauses")]}),

  "articles-determiners": topic({ name: "Articles & Determiners", description: "Countability, definiteness, genericity, and discourse reference.", controlledSites: ["article/determiner", "noun countability", "specificity or discourse reference"], forbidden: ["both articles licensed by missing context", "regional institutional-article variation", "proper-name conventions without stable rule"], distractors: "Use generic/specific confusion, countability transfer, and first/subsequent mention errors.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Best Revision", "Contextual Usage"],
    easy: [c("a-an-sound", "Indefinite Articles", "Surface Agreement", "Article follows initial sound"), c("first-subsequent-mention", "Definite Article", "Contextual Fit Trap", "Indefinite introduction then definite reference"), c("zero-generic-plural", "Zero Article", "Overgeneralized Rule", "Generic plural or mass noun"), c("demonstrative-distance", "Demonstratives", "Contextual Fit Trap", "Number and discourse location"), c("basic-quantifier", "Quantifiers", "Countability Confusion", "Count/mass-compatible quantifier")],
    moderate: [c("generic-specific", "Generic Reference", "Meaning-Grammar Conflict", "Generic class versus identified member"), c("count-mass-article", "Specific vs General Reference", "Countability Confusion", "Count reading created by context"), c("proper-name-article", "Article Use with Proper Nouns", "Exception Blindness", "Stable geographical/institutional convention"), c("predeterminer-order", "Predeterminers", "Wrong Word Form", "All/both/half determiner order"), c("quantifier-reference", "Quantifiers", "Contextual Fit Trap", "Few/a few or little/a little meaning")],
    hard: [c("countability-specificity", "Specific vs General Reference", "Rule Collision", "Countability plus discourse specificity"), c("genericity-reference-chain", "Generic Reference", "Partial Correction", "Generic statement followed by specific anaphoric reference"), c("proper-name-common-use", "Article Use with Proper Nouns", "Meaning-Grammar Conflict", "Proper name shifted to count/common-noun use"), c("determiner-quantifier-stack", "Predeterminers", "Rule Collision", "Predeterminer plus article/possessive and quantifier"), c("multi-noun-article-system", "Zero Article", "Rule Collision", "Different article decisions across linked nouns")]}),

  "verbs-auxiliaries": topic({ name: "Verbs & Auxiliaries", description: "Verb function, finiteness, transitivity, auxiliaries, and complementation.", controlledSites: ["verb/auxiliary form", "finiteness or transitivity", "licensed complement"], forbidden: ["lexical preference presented as grammar", "transitivity without intended meaning", "dialect-dependent auxiliary variants"], distractors: "Use auxiliary/main confusion, invalid do-support, and complement-frame substitution.", questionTypes: ["Sentence Correction", "Error Detection", "Fill in the Blank", "Best Revision"],
    easy: [c("main-auxiliary", "Main vs Auxiliary Verbs", "Misleading Familiarity", "Identify auxiliary function"), c("primary-auxiliary-form", "Primary Auxiliaries", "Wrong Word Form", "Be/have/do form in verb phrase"), c("do-support", "Do-Support", "Overgeneralized Rule", "Negation or question with lexical verb"), c("finite-nonfinite", "Finite and Non-Finite Verbs", "Wrong Word Form", "Finite carrier versus non-finite complement"), c("linking-complement", "Linking Verbs", "Contextual Fit Trap", "Subject complement after linking verb")],
    moderate: [c("transitivity-frame", "Transitivity", "Contextual Fit Trap", "Object requirement tied to intended sense"), c("stative-progressive", "Stative vs Dynamic Verbs", "Meaning-Grammar Conflict", "Dynamic reading licenses progressive"), c("causative-pattern", "Causative Verbs", "Wrong Word Form", "Make/have/get complement pattern"), c("verb-complement", "Verb Complementation", "Idiomatic Usage Trap", "Gerund/infinitive/clause frame"), c("auxiliary-sequence", "Primary Auxiliaries", "Partial Correction", "Ordered auxiliaries and participles")],
    hard: [c("auxiliary-finiteness", "Finite and Non-Finite Verbs", "Rule Collision", "Finiteness across embedded verb chains"), c("transitivity-voice", "Transitivity", "Meaning-Grammar Conflict", "Sense-specific transitivity plus passive possibility"), c("stative-sense-aspect", "Stative vs Dynamic Verbs", "Contextual Fit Trap", "Lexical sense plus aspect"), c("causative-complement-chain", "Causative Verbs", "Rule Collision", "Causative plus passive/non-finite complement"), c("multi-frame-revision", "Verb Complementation", "Partial Correction", "Two verbs requiring different complement frames")]}),

  tenses: topic({ name: "Tenses", description: "Tense, aspect, event order, temporal markers, and narrative consistency.", controlledSites: ["tense", "aspect", "event-time relationship and temporal evidence"], forbidden: ["multiple defensible timelines", "tense chosen without time evidence", "tense and aspect conflated", "reported-speech items that mix a specific past event with an ongoing or habitual marker unless an explicit time boundary makes only one timeline possible"], distractors: "Use temporal-marker attraction, premature perfect, and narrative-time shifts.", questionTypes: ["Sentence Correction", "Fill in the Blank", "Error Detection", "Best Revision"], productionReady: true,
    easy: [c("present-time", "Present Time", "Tense Attraction", "Habit versus current event"), c("past-time", "Past Time", "Tense Attraction", "Completed past with explicit marker"), c("future-reference", "Future Reference", "Contextual Fit Trap", "Scheduled, predicted, or intended future"), c("basic-perfect", "Perfect Aspect", "Tense Attraction", "Prior event linked to reference time"), c("basic-progressive", "Progressive Aspect", "Wrong Word Form", "Ongoing bounded event")],
    moderate: [c("sequence-report", "Sequence of Tenses", "Tense Attraction", "Main and subordinate temporal alignment"), c("time-clause", "Time-Clause Restrictions", "Overgeneralized Rule", "Future meaning without will in time clause"), c("narrative-background", "Narrative Tenses", "Contextual Fit Trap", "Background versus foreground event"), c("perfect-progressive", "Perfect Aspect", "Rule Collision", "Duration plus current relevance"), c("stative-restriction", "Stative Verb Restrictions", "Meaning-Grammar Conflict", "State versus temporary dynamic sense")],
    hard: [c("aspect-event-order", "Perfect Aspect", "Rule Collision", "Aspect plus three-event ordering"), c("narrative-sequence", "Narrative Tenses", "Partial Correction", "Narrative frame with anterior and ongoing events"), c("future-time-clause-aspect", "Time-Clause Restrictions", "Rule Collision", "Future reference plus completed prerequisite"), c("stative-sense-sequence", "Stative Verb Restrictions", "Meaning-Grammar Conflict", "Lexical sense plus sequence"), c("multi-clause-consistency", "Tense Consistency", "Rule Collision", "Distinct justified tenses across clauses")]}),

  modals: topic({ name: "Modals", description: "Modal form and recoverable meanings of possibility, obligation, advice, and deduction.", controlledSites: ["modal form", "time reference", "modal meaning and evidence"], forbidden: ["vague speaker intention", "equally plausible modal meanings", "prescriptive strength without context"], distractors: "Use strength-of-modality confusion, time mismatch, and modal-perfect form errors.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Contextual Usage", "Best Revision"],
    easy: [c("ability", "Ability", "Contextual Fit Trap", "Present or past ability with evidence"), c("permission", "Permission", "Misleading Familiarity", "Permission versus ability"), c("obligation", "Obligation", "Meaning-Grammar Conflict", "External rule versus optional action"), c("advice", "Advice", "Semantic Plausibility Trap", "Recommendation strength"), c("possibility", "Possibility", "Contextual Fit Trap", "Open possibility")],
    moderate: [c("probability-evidence", "Probability", "Meaning-Grammar Conflict", "Likelihood calibrated by evidence"), c("necessity-obligation", "Necessity", "Rule Collision", "Logical necessity versus imposed obligation"), c("present-deduction", "Deduction", "Semantic Plausibility Trap", "Must/can't/might from stated evidence"), c("past-modal", "Past Modals", "Tense Attraction", "Past ability/permission or habitual possibility"), c("modal-perfect", "Modal Perfect", "Wrong Word Form", "Modal plus have plus participle")],
    hard: [c("modal-perfect-deduction", "Modal Perfect", "Rule Collision", "Past deduction plus degree of certainty"), c("counterfactual-obligation", "Past Modals", "Meaning-Grammar Conflict", "Unfulfilled duty versus criticism"), c("time-shift-modality", "Probability", "Tense Attraction", "Different modal time references across clauses"), c("permission-deduction-collision", "Deduction", "Rule Collision", "Same modal form distinguished by context"), c("multi-modal-revision", "Necessity", "Partial Correction", "Two sites requiring different modality strengths")]}),

  "gerunds-infinitives-participles": topic({ name: "Gerunds, Infinitives & Participles", description: "Non-finite form, complement selection, attachment, and meaning differences.", controlledSites: ["non-finite form", "licensing verb/construction", "attachment or temporal relation"], forbidden: ["lexical pattern without stable convention", "dangling-participle referent guesses", "meaning change not established"], distractors: "Use plausible competing non-finite forms and attachment errors.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Error Detection", "Best Revision"],
    easy: [c("gerund-complement", "Gerund Usage", "Wrong Word Form", "Verb requiring gerund"), c("to-infinitive", "To-Infinitive Usage", "Wrong Word Form", "Verb requiring to-infinitive"), c("bare-infinitive", "Bare Infinitive", "Overgeneralized Rule", "Modal or causative bare infinitive"), c("present-participle", "Present Participles", "Modifier Attachment", "Active participial relation"), c("past-participle", "Past Participles", "Wrong Word Form", "Passive/resultative participle")],
    moderate: [c("verb-pattern", "Verb Pattern Selection", "Idiomatic Usage Trap", "Gerund versus infinitive frame"), c("meaning-change-complement", "Meaning Change by Complement", "Meaning-Grammar Conflict", "Remember/stop/try meaning contrast"), c("perfect-participle", "Perfect Participles", "Tense Attraction", "Completed prior participial event"), c("participle-attachment", "Dangling Participles", "Modifier Attachment", "Explicit logical subject"), c("passive-infinitive", "To-Infinitive Usage", "Rule Collision", "Active versus passive infinitive")],
    hard: [c("pattern-meaning-time", "Meaning Change by Complement", "Rule Collision", "Complement form plus temporal interpretation"), c("perfect-passive-nonfinite", "Perfect Participles", "Rule Collision", "Perfect and passive non-finite structure"), c("control-attachment", "Dangling Participles", "Modifier Attachment", "Matrix subject and non-finite understood subject"), c("causative-bare-passive", "Bare Infinitive", "Partial Correction", "Causative pattern plus passive transformation"), c("multi-nonfinite-chain", "Verb Pattern Selection", "Rule Collision", "Nested verbs licensing different non-finite forms")]}),

  prepositions: topic({ name: "Prepositions", description: "Governed and semantic preposition choice, phrase structure, and redundancy.", controlledSites: ["preposition", "governing word", "semantic relation or complement"], forbidden: ["regional alternatives", "multiple idiomatic variants", "preposition choice without sufficient spatial/temporal context"], distractors: "Use near semantic neighbors and common dependency substitutions.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Error Detection", "Contextual Usage"],
    easy: [c("time-preposition", "Time Prepositions", "Contextual Fit Trap", "Point, day, or period relation"), c("place-preposition", "Place Prepositions", "Contextual Fit Trap", "Container, surface, or point"), c("movement-preposition", "Movement Prepositions", "Meaning-Grammar Conflict", "Path versus destination"), c("basic-dependent", "Dependent Prepositions", "Idiomatic Usage Trap", "Stable adjective/verb dependency"), c("redundant-preposition", "Redundant Prepositions", "Redundancy Trap", "Unlicensed extra preposition")],
    moderate: [c("time-boundary", "Time Prepositions", "Meaning-Grammar Conflict", "Since/for/by/until with timeline"), c("spatial-perspective", "Place Prepositions", "Semantic Plausibility Trap", "Position relative to boundary or area"), c("verb-sense-dependency", "Dependent Prepositions", "Contextual Fit Trap", "Verb sense changes governed preposition"), c("phrase-attachment", "Prepositional Phrases", "Modifier Attachment", "Prepositional phrase attachment"), c("stranding-context", "Stranded Prepositions", "Overgeneralized Rule", "Licensed stranding versus malformed dependency")],
    hard: [c("temporal-spatial-metaphor", "Preposition Choice", "Rule Collision", "Metaphorical relation plus governed dependency"), c("multiple-dependencies", "Dependent Prepositions", "Partial Correction", "Two heads requiring different prepositions"), c("attachment-meaning", "Prepositional Phrases", "Modifier Attachment", "Placement determines semantic relation"), c("stranding-relative", "Stranded Prepositions", "Rule Collision", "Relative construction plus complement requirement"), c("redundancy-dependency", "Redundant Prepositions", "Idiomatic Usage Trap", "Required versus duplicated preposition across coordination")]}),

  conjunctions: topic({ name: "Conjunctions", description: "Coordination, subordination, correlation, and explicit logical relationships.", controlledSites: ["conjunction", "linked constituents", "logical relation and pairing"], forbidden: ["logical relation underdetermined", "punctuation-only disputes", "paired forms with multiple standard variants"], distractors: "Use wrong logical connectors, incomplete pairs, and category mismatches.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Best Revision", "Error Detection"],
    easy: [c("coordinate-relation", "Coordinating Conjunctions", "Contextual Fit Trap", "Addition, contrast, or result"), c("subordinate-relation", "Subordinating Conjunctions", "Meaning-Grammar Conflict", "Time, cause, condition, or concession"), c("basic-correlative", "Correlative Conjunctions", "Partial Correction", "Complete paired conjunction"), c("logical-choice", "Logical Relationship", "Semantic Plausibility Trap", "Connector matches stated relation"), c("redundant-connector", "Redundant Conjunctions", "Redundancy Trap", "Although/but or because/so duplication")],
    moderate: [c("correlative-pairing", "Conjunction Pairing", "Misleading Familiarity", "Not only/but also and either/or pairing"), c("category-coordination", "Coordinating Conjunctions", "False Parallelism", "Conjunction links equivalent units"), c("concession-cause", "Subordinating Conjunctions", "Meaning-Grammar Conflict", "Competing logical signals"), c("conjunctive-adverb", "Conjunctive Adverbs", "Wrong Word Form", "Conjunctive adverb versus conjunction structure"), c("embedded-relation", "Logical Relationship", "Modifier Attachment", "Connector scope in embedded clause")],
    hard: [c("multi-relation-chain", "Logical Relationship", "Rule Collision", "Different relations across coordinated clauses"), c("correlative-scope", "Correlative Conjunctions", "Modifier Attachment", "Pair placement and scope"), c("subordination-reference", "Subordinating Conjunctions", "Semantic Plausibility Trap", "Temporal/causal relation with event order"), c("conjunctive-punctuation-logic", "Conjunctive Adverbs", "Rule Collision", "Clause status plus logical connector"), c("pairing-parallelism", "Conjunction Pairing", "False Parallelism", "Correct pair plus structurally parallel complements")]}),

  "clauses-phrases": topic({ name: "Clauses & Phrases", description: "Clause type, constituent function, restriction, and reduction.", controlledSites: ["constituent boundary", "finite/non-finite status", "clause or phrase function"], forbidden: ["classification without full sentence", "relative restriction dependent on missing context", "reduction that changes subject"], distractors: "Use similar surface forms with different functions and invalid reductions.", questionTypes: ["Contextual Usage", "Correct Sentence", "Sentence Correction", "Best Revision"],
    easy: [c("independent-dependent", "Independent and Dependent Clauses", "Surface Agreement", "Finite completeness"), c("phrase-clause", "Phrase vs Clause", "Wrong Word Form", "Presence of subject-predicate structure"), c("noun-clause", "Noun Clauses", "Contextual Fit Trap", "Clause fills noun position"), c("relative-clause", "Relative Clauses", "Pronoun Reference Confusion", "Clause modifies explicit noun"), c("adverbial-clause", "Adverbial Clauses", "Meaning-Grammar Conflict", "Clause expresses circumstance")],
    moderate: [c("restrictive-context", "Restrictive vs Non-Restrictive Clauses", "Contextual Fit Trap", "Identity-defining versus supplementary information"), c("clause-function", "Clause Function", "Modifier Attachment", "Same marker with different clause role"), c("reduced-relative", "Reduced Clauses", "Wrong Word Form", "Valid subject-preserving reduction"), c("embedded-noun-clause", "Noun Clauses", "Misleading Familiarity", "Statement word order in embedded question"), c("relative-attachment", "Relative Clauses", "Modifier Attachment", "Unique modified antecedent")],
    hard: [c("nested-function", "Clause Function", "Rule Collision", "Nested clauses with distinct functions"), c("reduction-voice-time", "Reduced Clauses", "Rule Collision", "Reduction preserves voice and temporal relation"), c("restriction-reference", "Restrictive vs Non-Restrictive Clauses", "Meaning-Grammar Conflict", "Restriction plus referent identity"), c("phrase-clause-parallel", "Phrase vs Clause", "False Parallelism", "Coordinated constituents require compatible status"), c("multi-clause-revision", "Independent and Dependent Clauses", "Partial Correction", "Repair subordination and attachment without meaning change")]}),

  conditionals: topic({ name: "Conditionals", description: "Conditional form, time reference, modality, inversion, and mixed relationships.", controlledSites: ["condition clause", "result clause", "time/modal relationship"], forbidden: ["timeline not established", "mixed conditional with multiple readings", "will-in-if prohibition applied mechanically"], distractors: "Use wrong time pairing, modal strength, and unreal/real interpretation.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Best Revision", "Error Detection"],
    easy: [c("zero-conditional", "Zero Conditional", "Tense Attraction", "General condition and result"), c("first-conditional", "First Conditional", "Tense Attraction", "Real future possibility"), c("second-conditional", "Second Conditional", "Meaning-Grammar Conflict", "Present/future unreal condition"), c("third-conditional", "Third Conditional", "Wrong Word Form", "Past counterfactual"), c("basic-consistency", "Conditional Tense Consistency", "Partial Correction", "Matching condition and result")],
    moderate: [c("mixed-past-present", "Mixed Conditionals", "Rule Collision", "Past condition with present result"), c("mixed-present-past", "Mixed Conditionals", "Meaning-Grammar Conflict", "Persistent condition with past result"), c("inverted-conditional", "Inverted Conditionals", "Surface Agreement", "Had/were/should inversion"), c("modal-variation", "Implied Conditions", "Contextual Fit Trap", "Result modality recoverable from context"), c("time-clause-consistency", "Conditional Tense Consistency", "Tense Attraction", "Conditional embedded in time sequence")],
    hard: [c("mixed-time-evidence", "Mixed Conditionals", "Rule Collision", "Explicit past and present evidence"), c("inversion-modality", "Inverted Conditionals", "Rule Collision", "Inversion plus modal result"), c("implied-condition", "Implied Conditions", "Semantic Plausibility Trap", "Condition encoded without if"), c("counterfactual-chain", "Third Conditional", "Partial Correction", "Linked counterfactual causes and results"), c("multi-conditional-revision", "Conditional Tense Consistency", "Rule Collision", "Different conditional relationships in one revision")]}),

  "sentence-structure-word-order": topic({ name: "Sentence Structure & Word Order", description: "Canonical order, inversion, fronting, clefts, emphasis, and placement.", controlledSites: ["constituent position", "triggering construction", "scope or information focus"], forbidden: ["stylistic preference without grammar consequence", "fronting with unclear focus", "inversion trigger absent"], distractors: "Use canonical-order attraction, misplaced objects/adverbs, and incomplete inversion.", questionTypes: ["Sentence Correction", "Best Revision", "Correct Sentence", "Error Detection"],
    easy: [c("basic-svo", "Basic Word Order", "Surface Agreement", "Subject-verb-object order"), c("question-order", "Question Word Order", "Wrong Word Form", "Auxiliary-subject inversion"), c("adverb-placement", "Adverb Placement", "Modifier Attachment", "Adverb near intended target"), c("object-placement", "Object Placement", "Contextual Fit Trap", "Object relative to particles/complements"), c("basic-emphasis", "Emphasis", "Misleading Familiarity", "Do-emphasis form")],
    moderate: [c("negative-inversion", "Negative Inversion", "Rule Collision", "Fronted negative trigger"), c("locative-inversion", "Inversion", "Surface Agreement", "Fronted locative and post-verbal subject"), c("fronting-focus", "Fronting", "Modifier Attachment", "Fronted constituent retains relation"), c("cleft-choice", "Cleft Sentences", "Contextual Fit Trap", "It/what cleft matching focus"), c("particle-object", "Object Placement", "Idiomatic Usage Trap", "Pronoun object with separable particle")],
    hard: [c("negative-inversion-aux", "Negative Inversion", "Rule Collision", "Trigger plus tense-appropriate auxiliary"), c("fronting-attachment", "Fronting", "Modifier Attachment", "Fronted phrase plus unambiguous attachment"), c("cleft-reference", "Cleft Sentences", "Meaning-Grammar Conflict", "Cleft focus plus reference preservation"), c("multi-adverb-scope", "Adverb Placement", "Rule Collision", "Several adverbs with distinct scopes"), c("emphasis-order-revision", "Emphasis", "Partial Correction", "Emphasis construction plus embedded word order")]}),

  modifiers: topic({ name: "Modifiers", description: "Modifier attachment, placement, scope, and logical subject.", controlledSites: ["modifier span", "modified constituent", "placement and intended meaning"], forbidden: ["two plausible attachment targets", "revision changes intended fact", "style-only placement preference"], distractors: "Use nearest-noun attraction, missing logical subjects, and scope shifts.", questionTypes: ["Best Revision", "Sentence Correction", "Error Detection", "Correct Sentence"], productionReady: true,
    easy: [c("misplaced-word", "Misplaced Modifiers", "Modifier Attachment", "Modifier placed beside target"), c("dangling-intro", "Dangling Modifiers", "Modifier Attachment", "Introductory modifier has logical subject"), c("limiting-placement", "Limiting Modifiers", "Meaning-Grammar Conflict", "Only/almost/even scope"), c("participial-target", "Participial Modifiers", "Modifier Attachment", "Participial phrase modifies explicit noun"), c("relative-attachment", "Relative Clause Attachment", "Pronoun Reference Confusion", "Relative clause beside antecedent")],
    moderate: [c("squinting-repair", "Squinting Modifiers", "Modifier Attachment", "Adverb placement resolves two-way scope"), c("multiple-candidate-attachment", "Ambiguous Modification", "Modifier Attachment", "Revision names intended target"), c("limiter-meaning", "Modifier Scope", "Meaning-Grammar Conflict", "Placement preserves intended proposition"), c("embedded-dangler", "Dangling Modifiers", "Partial Correction", "Logical subject across passive/embedded clause"), c("relative-scope", "Relative Clause Attachment", "Pronoun Reference Confusion", "Attachment plus restrictive meaning")],
    hard: [c("attachment-scope", "Modifier Scope", "Rule Collision", "Attachment and scope independently controlled"), c("participial-reference", "Participial Modifiers", "Modifier Attachment", "Participial logic plus pronoun reference"), c("multi-modifier-order", "Misplaced Modifiers", "Partial Correction", "Two modifiers require distinct placements"), c("squinting-limiter", "Squinting Modifiers", "Meaning-Grammar Conflict", "Frequency/limiting modifier scope interaction"), c("meaning-preserving-revision", "Ambiguous Modification", "Rule Collision", "Resolve attachment without changing relations")]}),

  parallelism: topic({ name: "Parallelism", description: "Grammatical and logical equivalence across coordinated structures.", controlledSites: ["coordinated elements", "grammatical form", "semantic role and scope"], forbidden: ["style-only symmetry", "different forms that are both grammatically licensed", "parallel grammar masking illogical meaning"], distractors: "Use partial parallelism, mismatched complement frames, and false semantic equivalence.", questionTypes: ["Sentence Correction", "Best Revision", "Error Detection", "Correct Sentence"],
    easy: [c("word-list", "Word-Level Parallelism", "False Parallelism", "List members share word class"), c("phrase-list", "Phrase-Level Parallelism", "Wrong Word Form", "Coordinated phrases share form"), c("clause-pair", "Clause-Level Parallelism", "Partial Correction", "Coordinated clauses share structure"), c("correlative-basic", "Correlative Parallelism", "False Parallelism", "Elements after paired conjunctions align"), c("comparison-basic", "Comparison Parallelism", "Semantic Plausibility Trap", "Compared elements share role")],
    moderate: [c("verb-complement-series", "Phrase-Level Parallelism", "Idiomatic Usage Trap", "Shared versus repeated complement markers"), c("nested-list", "List Parallelism", "Partial Correction", "List contains embedded coordinated unit"), c("correlative-scope", "Correlative Parallelism", "Modifier Attachment", "Pair placement aligns full constituents"), c("clause-ellipsis", "Clause-Level Parallelism", "Misleading Familiarity", "Licensed ellipsis preserves structure"), c("logical-role", "Logical Parallelism", "Meaning-Grammar Conflict", "Grammatical forms express equivalent roles")],
    hard: [c("grammar-logic-interaction", "Logical Parallelism", "Rule Collision", "Formal and semantic parallelism both required"), c("nested-correlative", "Correlative Parallelism", "False Parallelism", "Correlative structure inside coordination"), c("comparison-ellipsis", "Comparison Parallelism", "Semantic Plausibility Trap", "Ellipsis preserves comparable terms"), c("multi-level-list", "List Parallelism", "Partial Correction", "Parallelism at two nesting levels"), c("complement-frame-parallel", "Phrase-Level Parallelism", "Rule Collision", "Different governing verbs and complement frames")]}),

  comparisons: topic({ name: "Comparisons", description: "Comparative form, logical comparison sets, scope, and than/as structures.", controlledSites: ["comparative construction", "compared entities", "scope and omitted material"], forbidden: ["comparison set implied only by world knowledge", "optional formal variants treated as errors", "ambiguous ellipsis"], distractors: "Use incomparable entities, double marking, and scope/ellipsis traps.", questionTypes: ["Sentence Correction", "Best Revision", "Error Detection", "Fill in the Blank"],
    easy: [c("comparative-form", "Comparative Forms", "Wrong Word Form", "Regular/irregular comparative"), c("superlative-set", "Superlative Forms", "Contextual Fit Trap", "Superlative within explicit set"), c("like-as", "Like vs As", "Wrong Word Form", "Noun comparison versus clause"), c("double-comparative", "Double Comparatives", "Overgeneralized Rule", "Single comparative marking"), c("basic-logical", "Logical Comparison", "Meaning-Grammar Conflict", "Like entities compared")],
    moderate: [c("than-ellipsis", "Than Structures", "Misleading Familiarity", "Recoverable omitted predicate"), c("possessive-comparison", "Logical Comparison", "Semantic Plausibility Trap", "Person's attribute versus person"), c("incomplete-standard", "Incomplete Comparisons", "Contextual Fit Trap", "Explicit comparison standard required"), c("scope-modifier", "Comparison Scope", "Modifier Attachment", "Degree/frequency scope"), c("superlative-reference", "Superlative Forms", "Meaning-Grammar Conflict", "Set membership and article/reference")],
    hard: [c("ellipsis-case-logic", "Than Structures", "Rule Collision", "Ellipsis plus intended comparison relation"), c("scope-set", "Comparison Scope", "Modifier Attachment", "Scope determines comparison set"), c("multi-entity-logic", "Logical Comparison", "Semantic Plausibility Trap", "Parallel comparison across linked entities"), c("comparative-superlative-context", "Comparative Forms", "Contextual Fit Trap", "Two-member versus larger explicit set"), c("meaning-preserving-comparison", "Incomplete Comparisons", "Partial Correction", "Complete standard without altering claim")]}),

  "active-passive-voice": topic({ name: "Active & Passive Voice", description: "Voice transformation with tense, aspect, argument structure, and meaning preservation.", controlledSites: ["auxiliary chain", "past participle", "agent/patient roles and transitivity"], forbidden: ["passivizing intransitive verbs", "meaning-changing agent insertion", "tense/aspect loss"], distractors: "Use malformed auxiliary chains, role reversal, and illicit passives.", questionTypes: ["Sentence Correction", "Best Revision", "Error Detection", "Correct Sentence"], productionReady: true,
    easy: [c("active-passive-basic", "Active to Passive Transformation", "Wrong Word Form", "Object becomes passive subject"), c("passive-active-basic", "Passive to Active Transformation", "Meaning-Grammar Conflict", "Recover roles from by-phrase"), c("tense-preservation", "Tense Preservation", "Tense Attraction", "Simple tense retained"), c("agent-omission", "Agent Omission", "Contextual Fit Trap", "Omit unknown/unimportant agent"), c("modal-passive", "Modal Passives", "Wrong Word Form", "Modal plus be plus participle")],
    moderate: [c("perfect-passive", "Tense Preservation", "Rule Collision", "Perfect aspect in passive"), c("progressive-passive", "Complex Passives", "Wrong Word Form", "Progressive passive auxiliary order"), c("ditransitive-passive", "Active to Passive Transformation", "Meaning-Grammar Conflict", "Licensed object promoted"), c("impersonal-passive", "Impersonal Passive", "Contextual Fit Trap", "It-passive versus personal passive"), c("get-passive-context", "Get-Passive", "Meaning-Grammar Conflict", "Affected-subject interpretation")],
    hard: [c("modal-perfect-passive", "Modal Passives", "Rule Collision", "Modal perfect plus passive"), c("complex-role-preservation", "Passive to Active Transformation", "Partial Correction", "Nested roles and reference preserved"), c("transitivity-constraint", "Active to Passive Transformation", "Semantic Plausibility Trap", "Sense-specific transitivity controls passivization"), c("impersonal-raising", "Impersonal Passive", "Rule Collision", "Reporting passive and infinitive time"), c("multi-auxiliary-voice", "Complex Passives", "Rule Collision", "Tense, aspect, modality, and voice chain")]}),

  "direct-indirect-speech": topic({ name: "Direct & Indirect Speech", description: "Reporting form, backshift, pronoun/reference, time/place, and speech-act type.", controlledSites: ["reporting verb", "reported clause form", "tense/pronoun/time-place reference"], forbidden: ["reporting time omitted when backshift matters", "deictic changes guessed without context", "meaning-changing reporting verb"], distractors: "Use partial backshift, unchanged question order, and wrong deictic/reference shifts.", questionTypes: ["Sentence Correction", "Best Revision", "Error Detection", "Fill in the Blank"],
    easy: [c("statement-report", "Statement Reporting", "Tense Attraction", "That-clause statement report"), c("question-report", "Question Reporting", "Wrong Word Form", "Statement order in reported question"), c("command-report", "Command Reporting", "Wrong Word Form", "Tell/ask plus object and infinitive"), c("pronoun-shift", "Pronoun Shift", "Pronoun Reference Confusion", "Speaker/addressee made explicit"), c("time-place-shift", "Time and Place Shift", "Contextual Fit Trap", "Deictic context explicitly changed")],
    moderate: [c("backshift-sequence", "Tense Backshift", "Tense Attraction", "Past reporting with prior/simultaneous event"), c("no-backshift-truth", "No-Backshift Contexts", "Overgeneralized Rule", "Still-valid fact with clear context"), c("reporting-verb-act", "Reporting Verb Choice", "Meaning-Grammar Conflict", "Question, command, promise, or advice"), c("reported-wh-question", "Question Reporting", "Partial Correction", "Wh-word plus statement order and reference"), c("command-reference", "Command Reporting", "Pronoun Reference Confusion", "Object, pronoun, and infinitive alignment")],
    hard: [c("backshift-reference-deixis", "Tense Backshift", "Rule Collision", "Backshift plus pronoun and time-place changes"), c("no-backshift-time", "No-Backshift Contexts", "Meaning-Grammar Conflict", "Current validity plus original event time"), c("embedded-question-report", "Question Reporting", "Rule Collision", "Question inside reported statement"), c("reporting-verb-complement", "Reporting Verb Choice", "Idiomatic Usage Trap", "Speech act plus licensed complement"), c("multi-speaker-revision", "Pronoun Shift", "Pronoun Reference Confusion", "Multiple speakers with uniquely recoverable references")]}),

  "question-tags": topic({ name: "Question Tags", description: "Tag polarity, auxiliary, pronoun, special subjects, imperatives, and meaning.", controlledSites: ["anchor clause polarity", "tag auxiliary", "tag pronoun and pragmatic force"], forbidden: ["intonation-only distinction without stated context", "regional tag variants", "lexical negation with unclear polarity"], distractors: "Use wrong auxiliary, surface subject repetition, and polarity misclassification.", questionTypes: ["Fill in the Blank", "Sentence Correction", "Error Detection", "Contextual Usage"],
    easy: [c("positive-negative", "Positive-Negative Polarity", "Surface Agreement", "Positive anchor takes negative tag"), c("auxiliary-copy", "Auxiliary Selection", "Wrong Word Form", "Existing auxiliary copied"), c("do-tag", "Auxiliary Selection", "Overgeneralized Rule", "Do-support for lexical verb"), c("pronoun-tag", "Pronoun Selection", "Pronoun Reference Confusion", "Tag pronoun represents subject"), c("lets-tag", "Let's Tags", "Exception Blindness", "Let's uses shall we")],
    moderate: [c("imperative-tag", "Imperative Tags", "Contextual Fit Trap", "Request/command tag with stated force"), c("indefinite-subject", "Indefinite Pronoun Tags", "Pronoun Reference Confusion", "Everyone/nobody tag pronoun"), c("special-there", "Special Subject Tags", "Exception Blindness", "Existential there retained"), c("negative-meaning-word", "Positive-Negative Polarity", "Meaning-Grammar Conflict", "Hardly/never/nobody counts negative"), c("modal-tag", "Auxiliary Selection", "Misleading Familiarity", "Modal anchor retained")],
    hard: [c("complex-polarity", "Positive-Negative Polarity", "Rule Collision", "Negative raising or semantically negative anchor"), c("special-subject-aux", "Special Subject Tags", "Exception Blindness", "This/that/nothing plus appropriate pronoun and auxiliary"), c("embedded-anchor", "Auxiliary Selection", "Rule Collision", "Tag attaches to correct matrix clause"), c("imperative-pragmatics", "Imperative Tags", "Contextual Fit Trap", "Tag form plus explicitly stated pragmatic force"), c("intonation-meaning", "Intonation and Meaning", "Meaning-Grammar Conflict", "Rising/falling meaning supplied in context")]}),

  "common-errors-usage": topic({ name: "Common Errors & Usage", description: "Diagnosable high-frequency errors organized by existing grammar skills.", controlledSites: ["specific error span", "governing rule", "literal correction and preserved meaning"], forbidden: ["arbitrary trivia", "style preference labeled error", "more than one unrelated unmarked error"], distractors: "Use one named misconception from the assigned skill, not miscellaneous bad grammar.", questionTypes: ["Error Detection", "Sentence Correction", "Best Revision", "Correct Sentence"],
    easy: [c("agreement-error", "Agreement Errors", "Proximity Attraction", "Single clear agreement error"), c("tense-error", "Tense Errors", "Tense Attraction", "Explicit temporal evidence"), c("pronoun-error", "Pronoun Errors", "Pronoun Reference Confusion", "Clear case/agreement/reference error"), c("article-error", "Article Errors", "Contextual Fit Trap", "Defensible article context"), c("word-form-error", "Word Form Errors", "Wrong Word Form", "Syntactically required form")],
    moderate: [c("modifier-error", "Modifier Errors", "Modifier Attachment", "Misplacement or dangling logic"), c("preposition-error", "Preposition Errors", "Idiomatic Usage Trap", "Stable governed preposition"), c("redundancy-error", "Redundancy", "Redundancy Trap", "Grammatical duplication not style"), c("idiom-error", "Idiomatic Usage", "Misleading Familiarity", "Stable edited-English construction"), c("confusable-context", "Confusable Words", "Contextual Fit Trap", "Meaning selects confusable word")],
    hard: [c("agreement-tense-interaction", "Agreement Errors", "Rule Collision", "Agreement correction without tense drift"), c("pronoun-modifier-interaction", "Pronoun Errors", "Modifier Attachment", "Reference plus attachment"), c("article-countability-error", "Article Errors", "Countability Confusion", "Article plus countability and specificity"), c("idiom-form-interaction", "Idiomatic Usage", "Wrong Word Form", "Idiomatic frame plus correct morphology"), c("integrated-error-revision", "Word Form Errors", "Multiple-Error Distraction", "Two related sites under one diagnosable pattern")]}),

  "sentence-correction-error-detection": topic({ name: "Sentence Correction & Error Detection", description: "Integrated diagnosis with format integrity, meaning preservation, and unique correction.", controlledSites: ["error segment", "corrected construction", "meaning and style boundary"], forbidden: ["multiple defensible corrections", "format/key mismatch", "pure style presented as grammar", "unmarked unrelated errors"], distractors: "Use partial corrections, no-error temptation, and plausible but meaning-changing revisions.", questionTypes: ["Error Detection", "Sentence Correction", "Multiple Error Detection", "Best Revision", "Correct Sentence"],
    easy: [c("single-error-identification", "Error Identification", "No-Error Temptation", "One literal erroneous segment"), c("single-correction", "Sentence Correction", "Partial Correction", "One targeted grammatical repair"), c("no-error", "No-Error Recognition", "No-Error Temptation", "Fully correct natural sentence"), c("grammar-style", "Grammar vs Style", "Misleading Familiarity", "Grammaticality distinguished from preference"), c("meaning-preservation", "Meaning Preservation", "Semantic Plausibility Trap", "Correction retains proposition")],
    moderate: [c("two-related-errors", "Multiple Error Detection", "Multiple-Error Distraction", "Two controlled related errors"), c("partial-correction", "Sentence Correction", "Partial Correction", "Distractor repairs only one site"), c("concise-grammar", "Conciseness", "Redundancy Trap", "Remove grammatical redundancy without loss"), c("logical-construction", "Logical Construction", "Meaning-Grammar Conflict", "Grammar and logical relation align"), c("style-versus-error", "Grammar vs Style", "No-Error Temptation", "Awkward but grammatical versus actual error")],
    hard: [c("integrated-two-mechanism", "Integrated Grammar Diagnosis", "Rule Collision", "Two interacting grammar mechanisms"), c("multiple-error-key", "Multiple Error Detection", "Multiple-Error Distraction", "All and only erroneous segments identified"), c("revision-meaning-logic", "Meaning Preservation", "Semantic Plausibility Trap", "Grammar repair preserves logic and scope"), c("concise-structure", "Conciseness", "Partial Correction", "Remove redundancy while maintaining required structure"), c("no-error-complex", "No-Error Recognition", "No-Error Temptation", "Complex but fully grammatical construction")]}),
}

for (const topicId of ["verbs-auxiliaries", "articles-determiners", "prepositions", "parallelism", "conjunctions", "conditionals"]) {
  GRAMMAR_TOPIC_BLUEPRINTS[topicId].productionReady = true
}

export function validateGrammarTopicBlueprints() {
  const errors = []
  const ontologyTopics = Object.keys(GRAMMAR_ONTOLOGY)
  for (const topicId of ontologyTopics) {
    const plan = GRAMMAR_TOPIC_BLUEPRINTS[topicId]
    if (!plan) { errors.push(`${topicId}: missing topic plan`); continue }
    if (!plan.description || !plan.controlledSites?.length || !plan.forbidden?.length || !plan.distractors) errors.push(`${topicId}: incomplete topic-level quality contract`)
    if (!Array.isArray(plan.questionTypes) || plan.questionTypes.some((value) => !GRAMMAR_QUESTION_TYPES.includes(value))) errors.push(`${topicId}: unknown question type`)
    for (const difficulty of ["easy", "moderate", "hard"]) {
      const constructions = plan.difficulties?.[difficulty]
      if (!Array.isArray(constructions) || constructions.length !== 5) { errors.push(`${topicId}/${difficulty}: expected five constructions`); continue }
      if (new Set(constructions.map((item) => item.id)).size !== 5) errors.push(`${topicId}/${difficulty}: duplicate construction id`)
      for (const construction of constructions) {
        if (!construction.id || !construction.focus) errors.push(`${topicId}/${difficulty}: incomplete construction`)
        if (!GRAMMAR_ONTOLOGY[topicId].skills.includes(construction.skill)) errors.push(`${topicId}/${difficulty}/${construction.id}: unknown skill '${construction.skill}'`)
        if (!GRAMMAR_TRAP_TYPES.includes(construction.trap)) errors.push(`${topicId}/${difficulty}/${construction.id}: unknown trap '${construction.trap}'`)
      }
    }
  }
  for (const topicId of Object.keys(GRAMMAR_TOPIC_BLUEPRINTS)) if (!GRAMMAR_ONTOLOGY[topicId]) errors.push(`${topicId}: plan has no ontology topic`)
  return { success: errors.length === 0, errors, topicCount: Object.keys(GRAMMAR_TOPIC_BLUEPRINTS).length, productionReady: Object.entries(GRAMMAR_TOPIC_BLUEPRINTS).filter(([, plan]) => plan.productionReady).map(([id]) => id), draft: Object.entries(GRAMMAR_TOPIC_BLUEPRINTS).filter(([, plan]) => !plan.productionReady).map(([id]) => id) }
}
