export const INBOX_TYPES = Object.freeze([
  "STUDY_REMINDER", "DAILY_RECOMMENDATION", "PERFORMANCE_UPDATE", "PROGRESS",
  "STREAK", "ACHIEVEMENT", "MILESTONE", "INACTIVITY", "EXAM_PREP",
  "FEATURE_UPDATE", "ACCOUNT", "OFFER", "TRIAL", "SYSTEM",
])

export const INBOX_FILTERS = Object.freeze({
  STUDY: ["STUDY_REMINDER", "DAILY_RECOMMENDATION", "EXAM_PREP"],
  PROGRESS: ["PERFORMANCE_UPDATE", "PROGRESS", "STREAK"],
  ACHIEVEMENTS: ["ACHIEVEMENT", "MILESTONE", "STREAK"],
  REMINDERS: ["STUDY_REMINDER", "INACTIVITY", "EXAM_PREP"],
  OFFERS: ["OFFER", "TRIAL"],
})

export const PROACTIVE_DAILY_TYPES = new Set([
  "STUDY_REMINDER", "DAILY_RECOMMENDATION", "PERFORMANCE_UPDATE", "PROGRESS",
  "STREAK", "INACTIVITY", "EXAM_PREP",
  "ACHIEVEMENT", "MILESTONE", "OFFER",
])
