-- Adds the existing authored vocabulary enrichment for Boot Camp days 1–16.
-- Existing enrichment values are preserved; only missing vocabulary keys are added.
-- Adds only enrichment.<passage-id>.vocabulary for passages missing that key.
-- Existing vocabulary is skipped; missing passage/enrichment objects abort.
begin;
do $vocabulary_patch$
declare
  item jsonb;
  target_document jsonb;
  changed integer;
  patch jsonb := $$[
    {"day":1,"passage":"bootcamp-day-1-rc1","vocabulary":[{"word":"intellectual illusion","contextualMeaning":"A belief that simplicity is self-evidently superior, despite hidden complexity.","whyAuthorUsedIt":"Names the mistaken confidence the passage examines."},{"word":"reductionism","contextualMeaning":"Explaining a complex matter by only one of its parts.","whyAuthorUsedIt":"Shows what is lost when a difficult idea is oversimplified."},{"word":"trade-off","contextualMeaning":"A gain in one respect that brings a cost in another.","whyAuthorUsedIt":"Frames simplicity as a choice with consequences."},{"word":"context","contextualMeaning":"The surrounding conditions that shape how an idea works.","whyAuthorUsedIt":"Emphasises why an apparently simple rule may fail elsewhere."}]},
    {"day":1,"passage":"bootcamp-day-1-rc2","vocabulary":[{"word":"procrastination","contextualMeaning":"Delaying an intended task despite expecting the delay to be costly.","whyAuthorUsedIt":"Identifies the behaviour the psychological account explains."},{"word":"temporal discounting","contextualMeaning":"Giving a smaller immediate reward more weight than a larger later one.","whyAuthorUsedIt":"Explains why present comfort can outweigh future benefit."},{"word":"self-regulation","contextualMeaning":"Managing attention and action to follow a longer-term intention.","whyAuthorUsedIt":"Connects intention with the difficulty of beginning work."},{"word":"avoidance","contextualMeaning":"Turning away from a task to escape its unpleasant feelings.","whyAuthorUsedIt":"Shows how postponement can relieve discomfort temporarily."}]},
    {"day":1,"passage":"bootcamp-day-1-rc3","vocabulary":[{"word":"Impressionism","contextualMeaning":"A painting movement attentive to changing light and momentary perception.","whyAuthorUsedIt":"Locates the passage's account of altered ways of seeing."},{"word":"optical conditions","contextualMeaning":"The circumstances of light, distance, and viewing that shape appearance.","whyAuthorUsedIt":"Links artistic choices to how scenes are perceived."},{"word":"modernity","contextualMeaning":"The changing social and material conditions of modern life.","whyAuthorUsedIt":"Places the movement within broader historical change."},{"word":"ephemeral","contextualMeaning":"Lasting only briefly; here, a passing visual impression.","whyAuthorUsedIt":"Highlights the movement's interest in transient experience."}]},
    {"day":2,"passage":"bootcamp-day-2-rc1","vocabulary":[{"word":"canopy","contextualMeaning":"The upper layer formed by tree branches and leaves.","whyAuthorUsedIt":"Identifies the urban feature whose shade is being assessed."},{"word":"proxy","contextualMeaning":"A measurable stand-in used to estimate something harder to measure.","whyAuthorUsedIt":"Distinguishes tree counts from actual cooling benefit."},{"word":"distribution","contextualMeaning":"The way trees or shade are spread across places and people.","whyAuthorUsedIt":"Directs attention from totals to unequal local access."},{"word":"microclimate","contextualMeaning":"The temperature and conditions of a small, specific area.","whyAuthorUsedIt":"Explains why local shade can matter beyond city averages."}]},
    {"day":2,"passage":"bootcamp-day-2-rc2","vocabulary":[{"word":"digitisation","contextualMeaning":"Converting collection materials and records into digital form.","whyAuthorUsedIt":"Describes the museum's technical step without implying access is solved."},{"word":"cataloguing","contextualMeaning":"Recording and organising information about collection items.","whyAuthorUsedIt":"Points to the hidden descriptive work behind searchable collections."},{"word":"metadata","contextualMeaning":"Structured information that describes an item and helps locate it.","whyAuthorUsedIt":"Shows why scans alone do not make objects discoverable."},{"word":"provenance","contextualMeaning":"The history of an object's ownership and movement.","whyAuthorUsedIt":"Signals the contextual record needed to interpret a collection item."}]},
    {"day":2,"passage":"bootcamp-day-2-rc3","vocabulary":[{"word":"pilot project","contextualMeaning":"A limited trial used to learn before wider implementation.","whyAuthorUsedIt":"Sets up the passage's question about scaling an intervention."},{"word":"scalability","contextualMeaning":"The ability to expand a project while retaining its intended effects.","whyAuthorUsedIt":"Names the challenge of carrying success into a larger setting."},{"word":"implementation","contextualMeaning":"Putting a plan into practice under real conditions.","whyAuthorUsedIt":"Separates a promising design from its actual delivery."},{"word":"context-dependent","contextualMeaning":"Working differently as local conditions change.","whyAuthorUsedIt":"Explains why results from a pilot may not transfer unchanged."}]},
    {"day":3,"passage":"bootcamp-day-3-rc1","vocabulary":[{"word":"presupposes","contextualMeaning":"Treats an unstated idea as already understood or accepted.","whyAuthorUsedIt":"Shows how jokes rely on shared background knowledge."},{"word":"propositional content","contextualMeaning":"The literal information a sentence states.","whyAuthorUsedIt":"Contrasts literal meaning with a joke's comic mechanism."},{"word":"incongruity","contextualMeaning":"A mismatch between an expectation and what occurs.","whyAuthorUsedIt":"Names the recognition that can trigger comic effect."},{"word":"social register","contextualMeaning":"A style of speech associated with a situation or relationship.","whyAuthorUsedIt":"Explains how humour communicates social positioning."}]},
    {"day":3,"passage":"bootcamp-day-3-rc2","vocabulary":[{"word":"reciprocity","contextualMeaning":"An expectation that giving or help will be answered in some form.","whyAuthorUsedIt":"Explains how a meal can establish continuing obligation."},{"word":"hospitality","contextualMeaning":"Welcoming a guest through culturally recognised practices.","whyAuthorUsedIt":"Shows that welcome can also define who counts as a guest."},{"word":"hierarchy","contextualMeaning":"An ordering of people by status or authority.","whyAuthorUsedIt":"Connects serving order and portions to social rank."},{"word":"embedded","contextualMeaning":"Situated within a relationship or social setting.","whyAuthorUsedIt":"Emphasises that food has no fixed meaning outside interaction."}]},
    {"day":3,"passage":"bootcamp-day-3-rc3","vocabulary":[{"word":"intermediaries","contextualMeaning":"People who connect imperial authorities with local communities.","whyAuthorUsedIt":"Identifies actors whose local knowledge made distant rule workable."},{"word":"jurisdiction","contextualMeaning":"The territory or matters over which authority applies.","whyAuthorUsedIt":"Distinguishes formal imperial reach from practical governing capacity."},{"word":"epistemically dependent","contextualMeaning":"Relying on others for the knowledge needed to understand or act.","whyAuthorUsedIt":"Highlights the centre's reliance on local information channels."},{"word":"contingent","contextualMeaning":"Dependent on conditions that may change.","whyAuthorUsedIt":"Characterises cooperation as conditional rather than permanent allegiance."}]},
    {"day":4,"passage":"bootcamp-day-4-rc1","vocabulary":[{"word":"statistically independent","contextualMeaning":"Events whose occurrence does not alter one another's probability in the model.","whyAuthorUsedIt":"Separates coincidence from a causal connection."},{"word":"intelligibility","contextualMeaning":"The quality of being understandable or making coherent sense.","whyAuthorUsedIt":"Shows how people turn scattered events into a story."},{"word":"self-sealing","contextualMeaning":"Structured so contrary evidence is reinterpreted instead of counted against it.","whyAuthorUsedIt":"Describes narratives that protect a pattern from challenge."},{"word":"disconfirmation","contextualMeaning":"Evidence that counts against a proposed explanation.","whyAuthorUsedIt":"Names the test needed to keep pattern claims falsifiable."}]},
    {"day":4,"passage":"bootcamp-day-4-rc2","vocabulary":[{"word":"egalitarianism","contextualMeaning":"A social arrangement that limits durable differences in rank or power.","whyAuthorUsedIt":"Frames the passage's account of Hadza social relations."},{"word":"mobility","contextualMeaning":"Movement between places as part of a way of life.","whyAuthorUsedIt":"Connects camp movement to social flexibility."},{"word":"deference","contextualMeaning":"Yielding authority or status to another person.","whyAuthorUsedIt":"Clarifies the social behaviour the passage contrasts with equality."},{"word":"foraging","contextualMeaning":"Obtaining food from wild plants and animals rather than cultivation.","whyAuthorUsedIt":"Situates the economic and social context under discussion."}]},
    {"day":4,"passage":"bootcamp-day-4-rc3","vocabulary":[{"word":"life-cycle costs","contextualMeaning":"Costs arising across a product's production, use, and disposal.","whyAuthorUsedIt":"Broadens evaluation beyond the purchase price."},{"word":"external costs","contextualMeaning":"Costs borne by people outside the immediate transaction.","whyAuthorUsedIt":"Makes hidden consequences part of the comparison."},{"word":"durability","contextualMeaning":"How long an item remains useful before replacement is needed.","whyAuthorUsedIt":"Connects product lifespan to total resource use."},{"word":"cheapness","contextualMeaning":"Low immediate price, which may not reflect total cost.","whyAuthorUsedIt":"Challenges price as a sufficient measure of value."}]},
    {"day":5,"passage":"bootcamp-day-5-rc1","vocabulary":[{"word":"frictionless","contextualMeaning":"Requiring very little effort or interruption to complete.","whyAuthorUsedIt":"Captures the consumer-facing appeal of delivery."},{"word":"rebound effect","contextualMeaning":"Increased use that follows an efficiency-driven reduction in effective cost.","whyAuthorUsedIt":"Explains why convenience may increase total consumption."},{"word":"embedded","contextualMeaning":"Built into the normal structure or expectations of a system.","whyAuthorUsedIt":"Shows how a preference can become infrastructure."},{"word":"redistribution","contextualMeaning":"A shifting of costs or resources among people or activities.","whyAuthorUsedIt":"Summarises convenience as moving costs rather than erasing them."}]},
    {"day":5,"passage":"bootcamp-day-5-rc2","vocabulary":[{"word":"anomaly","contextualMeaning":"An observation that differs from what was expected.","whyAuthorUsedIt":"Names the unexpected result that may prompt investigation."},{"word":"serendipity","contextualMeaning":"Finding something valuable through an unplanned observation.","whyAuthorUsedIt":"Complicates the idea that discovery is pure luck."},{"word":"framework","contextualMeaning":"A body of knowledge used to interpret observations.","whyAuthorUsedIt":"Explains why prepared researchers can recognise significance."},{"word":"replication","contextualMeaning":"Repeating a study to see whether its result recurs.","whyAuthorUsedIt":"Separates a suggestive accident from established evidence."}]},
    {"day":5,"passage":"bootcamp-day-5-rc3","vocabulary":[{"word":"social reinvention","contextualMeaning":"Recasting one's identity or position within society.","whyAuthorUsedIt":"Describes the promise Gatsby's wealth appears to offer."},{"word":"inherited status","contextualMeaning":"Social standing received through family background.","whyAuthorUsedIt":"Contrasts Gatsby's acquired wealth with old-money security."},{"word":"idealised","contextualMeaning":"Seen in an unrealistically perfected or desirable form.","whyAuthorUsedIt":"Shows how Gatsby's desire reshapes the past."},{"word":"aspiration","contextualMeaning":"A strong hope or ambition for a different future.","whyAuthorUsedIt":"Preserves the admirable side of the Dream's appeal."}]},
    {"day":6,"passage":"bootcamp-day-6-rc1","vocabulary":[{"word":"intervention","contextualMeaning":"A deliberate change made to a system to observe its effects.","whyAuthorUsedIt":"Defines the experimental action the passage evaluates."},{"word":"singular historical system","contextualMeaning":"A one-time past event that cannot be rerun as an experiment.","whyAuthorUsedIt":"Explains the evidential limits in cosmology and history."},{"word":"converging evidence","contextualMeaning":"Different kinds of observations pointing toward the same account.","whyAuthorUsedIt":"Shows how history can be tested without replaying events."},{"word":"epistemically destructive","contextualMeaning":"Damaging the very phenomenon one wants to know by intervening.","whyAuthorUsedIt":"Explains why some possible experiments undermine inquiry."}]},
    {"day":6,"passage":"bootcamp-day-6-rc2","vocabulary":[{"word":"symbolic memory","contextualMeaning":"A simplified public representation of the past used in the present.","whyAuthorUsedIt":"Distinguishes cultural symbols from complex historical lives."},{"word":"selection","contextualMeaning":"Choosing certain episodes while leaving others out.","whyAuthorUsedIt":"Identifies how a memorable public narrative is formed."},{"word":"portable","contextualMeaning":"Able to be reused in new settings with little reference to its origin.","whyAuthorUsedIt":"Explains why figures can serve competing later causes."},{"word":"under-determined","contextualMeaning":"Not settled by the available evidence; several accounts remain possible.","whyAuthorUsedIt":"Describes the uncertainty of reconstructing real motives."}]},
    {"day":6,"passage":"bootcamp-day-6-rc3","vocabulary":[{"word":"mutualism","contextualMeaning":"An interaction in which both participating species benefit.","whyAuthorUsedIt":"Names one form of ecological cooperation discussed."},{"word":"exploitation","contextualMeaning":"An interaction where one organism gains at another's cost.","whyAuthorUsedIt":"Shows how cooperation can shift with behaviour and conditions."},{"word":"equilibrium","contextualMeaning":"A condition maintained through ongoing interacting pressures.","whyAuthorUsedIt":"Presents cooperation as maintained, not negotiated harmony."},{"word":"prevailing conditions","contextualMeaning":"The environmental circumstances currently shaping an interaction.","whyAuthorUsedIt":"Explains why a relationship's costs and benefits can change."}]},
    {"day":7,"passage":"bootcamp-day-7-rc1","vocabulary":[{"word":"determinate","contextualMeaning":"Having one settled meaning or outcome.","whyAuthorUsedIt":"Sets up the claim that an understandable story can remain open."},{"word":"underdetermined","contextualMeaning":"Allowing more than one coherent interpretation from the evidence.","whyAuthorUsedIt":"Defines productive ambiguity without equating it with confusion."},{"word":"interpretive pressure","contextualMeaning":"The demand a text places on readers to weigh competing meanings.","whyAuthorUsedIt":"Distinguishes meaningful uncertainty from a mere missing answer."},{"word":"closure","contextualMeaning":"A resolution that settles the story's remaining questions.","whyAuthorUsedIt":"Explains how complete resolution can end interpretation."}]},
    {"day":7,"passage":"bootcamp-day-7-rc2","vocabulary":[{"word":"reputation","contextualMeaning":"Information about a person's past conduct known to others.","whyAuthorUsedIt":"Explains how costly help can affect future opportunities."},{"word":"proximate explanation","contextualMeaning":"An account of the immediate psychological cause of an action.","whyAuthorUsedIt":"Separates felt motives from an evolutionary account."},{"word":"free-riding","contextualMeaning":"Receiving the benefits of cooperation without contributing to it.","whyAuthorUsedIt":"Identifies a behaviour communities may discourage."},{"word":"cultural transmission","contextualMeaning":"The passing of practices and norms between people and generations.","whyAuthorUsedIt":"Shows how cooperation can spread beyond genes."}]},
    {"day":7,"passage":"bootcamp-day-7-rc3","vocabulary":[{"word":"hybridity","contextualMeaning":"The combining of cultural or visual forms from different traditions.","whyAuthorUsedIt":"Frames mixture as an intentional artistic method."},{"word":"ethnographic illustration","contextualMeaning":"Art treated as a documentary example of a culture.","whyAuthorUsedIt":"Warns against reducing Lam's paintings to cultural depiction."},{"word":"appropriation","contextualMeaning":"Adapting a form from another tradition for a new purpose.","whyAuthorUsedIt":"Describes how Cuban artists engage with modernist language."},{"word":"visual vocabulary","contextualMeaning":"A set of forms and techniques through which images communicate.","whyAuthorUsedIt":"Shows painting as a way to argue about cultural identity."}]},
    {"day":8,"passage":"bootcamp-day-8-rc1","vocabulary":[{"word":"reciprocal","contextualMeaning":"Operating in both directions, with each side affecting the other.","whyAuthorUsedIt":"Describes how humans and animals changed through domestication."},{"word":"selective environment","contextualMeaning":"Conditions that influence which traits aid survival and reproduction.","whyAuthorUsedIt":"Explains evolution without assuming deliberate human control."},{"word":"heritable","contextualMeaning":"Capable of being passed from one generation to the next.","whyAuthorUsedIt":"Distinguishes domestication from merely taming one animal."},{"word":"feedback process","contextualMeaning":"A cycle in which changes on each side affect later changes on the other.","whyAuthorUsedIt":"Captures the two-way development of domestication."}]},
    {"day":8,"passage":"bootcamp-day-8-rc2","vocabulary":[{"word":"material evidence","contextualMeaning":"Physical objects that can support claims about past life.","whyAuthorUsedIt":"Contrasts objects with institutionally preserved written records."},{"word":"archaeological visibility","contextualMeaning":"The likelihood that past activity leaves recoverable physical traces.","whyAuthorUsedIt":"Explains why surviving objects do not mirror historical importance."},{"word":"artefact","contextualMeaning":"An object made or used by people and recovered from the past.","whyAuthorUsedIt":"Names the evidence whose significance depends on context."},{"word":"repetition","contextualMeaning":"The recurrence of similar objects across many contexts.","whyAuthorUsedIt":"Shows how ordinary items can reveal larger systems."}]},
    {"day":8,"passage":"bootcamp-day-8-rc3","vocabulary":[{"word":"metacognition","contextualMeaning":"Awareness or monitoring of one's own mental state.","whyAuthorUsedIt":"Describes the reflective awareness found in lucid dreaming."},{"word":"physiological record","contextualMeaning":"Measured bodily signals recorded during sleep.","whyAuthorUsedIt":"Explains how researchers locate reported lucid periods."},{"word":"correspondence","contextualMeaning":"A relationship between a reported experience and a measurable signal.","whyAuthorUsedIt":"Clarifies what eye-movement evidence can establish."},{"word":"lucidity","contextualMeaning":"Awareness, during a dream, that the experience is a dream.","whyAuthorUsedIt":"Names the phenomenon while separating awareness from control."}]},
    {"day":9,"passage":"bootcamp-day-9-rc1","vocabulary":[{"word":"distributional consequences","contextualMeaning":"Effects on how gains or losses are divided among groups.","whyAuthorUsedIt":"Separates overall productivity from who benefits."},{"word":"nominally universal","contextualMeaning":"Presented as available to everyone in principle.","whyAuthorUsedIt":"Contrasts device access with unequal ability to use it."},{"word":"complementary infrastructure","contextualMeaning":"Supporting resources needed to make a technology useful.","whyAuthorUsedIt":"Shows why access depends on more than owning a device."},{"word":"durable advantage","contextualMeaning":"A benefit that can be maintained over time.","whyAuthorUsedIt":"Focuses on converting technology into lasting opportunity."}]},
    {"day":9,"passage":"bootcamp-day-9-rc2","vocabulary":[{"word":"proxy","contextualMeaning":"An indirect measure used in place of a broader outcome.","whyAuthorUsedIt":"Characterises GDP's use as a stand-in for social improvement."},{"word":"accounting convention","contextualMeaning":"A rule for deciding what economic activity is counted and how.","whyAuthorUsedIt":"Clarifies the scope of what GDP measures."},{"word":"diminishing gains","contextualMeaning":"Smaller added benefits from each further increase in consumption.","whyAuthorUsedIt":"Explains why more output may not improve life proportionally."},{"word":"distribution","contextualMeaning":"How economic resources and gains are shared across people.","whyAuthorUsedIt":"Shows why average income can hide unequal experience."}]},
    {"day":9,"passage":"bootcamp-day-9-rc3","vocabulary":[{"word":"pluripotent","contextualMeaning":"Able, under suitable conditions, to develop into many cell types.","whyAuthorUsedIt":"Defines the potential state produced by reprogramming."},{"word":"reprogramme","contextualMeaning":"Alter a mature cell's state so it behaves more like an earlier cell.","whyAuthorUsedIt":"Names the technique enabling patient-specific stem-cell models."},{"word":"disease model","contextualMeaning":"A simplified system used to study features of a disease.","whyAuthorUsedIt":"Explains how patient-derived cells support laboratory investigation."},{"word":"translation","contextualMeaning":"Moving findings from laboratory models toward clinical use.","whyAuthorUsedIt":"Names the challenge of applying cell results to human disease."}]},
    {"day":10,"passage":"bootcamp-day-10-rc1","vocabulary":[{"word":"scarcity","contextualMeaning":"Limited availability relative to demand or perceived need.","whyAuthorUsedIt":"Introduces the condition that can reshape perceived value."},{"word":"signal","contextualMeaning":"A cue people use to infer quality, demand, or status.","whyAuthorUsedIt":"Explains how limited supply communicates beyond utility."},{"word":"exclusivity","contextualMeaning":"Social meaning attached to restricted access or ownership.","whyAuthorUsedIt":"Distinguishes scarcity from status created by access limits."},{"word":"manufactured scarcity","contextualMeaning":"A deliberately created limitation in availability.","whyAuthorUsedIt":"Shows why rarity does not automatically create genuine value."}]},
    {"day":10,"passage":"bootcamp-day-10-rc2","vocabulary":[{"word":"cynicism","contextualMeaning":"A settled suspicion that claims are driven by self-interest or bad faith.","whyAuthorUsedIt":"Contrasts motive-focused suspicion with evidence-based doubt."},{"word":"epistemic function","contextualMeaning":"The role an attitude plays in how knowledge claims are assessed.","whyAuthorUsedIt":"Explains what doubt contributes to inquiry."},{"word":"refutation","contextualMeaning":"Evidence or reasoning that shows a claim to be false.","whyAuthorUsedIt":"Separates explaining a speaker's motive from disproving a claim."},{"word":"prior assumption","contextualMeaning":"A belief held before new evidence is considered.","whyAuthorUsedIt":"Shows how suspicion can predetermine interpretation."}]},
    {"day":10,"passage":"bootcamp-day-10-rc3","vocabulary":[{"word":"incongruity","contextualMeaning":"A mismatch that violates an audience's expectation.","whyAuthorUsedIt":"Identifies a comic mechanism that may cross cultures."},{"word":"presupposes","contextualMeaning":"Depends on knowledge that is not explicitly stated.","whyAuthorUsedIt":"Explains why audiences can miss context-dependent humour."},{"word":"substitution","contextualMeaning":"Replacing an original reference with one familiar to a new audience.","whyAuthorUsedIt":"Shows one trade-off translators make to preserve comic function."},{"word":"social recognition","contextualMeaning":"Shared awareness of references, norms, or relationships in a group.","whyAuthorUsedIt":"Explains why a joke requires more than translated words."}]},
    {"day":11,"passage":"bootcamp-day-11-rc1","vocabulary":[{"word":"interiority","contextualMeaning":"A person's inner thoughts, motives, and private experience.","whyAuthorUsedIt":"Contrasts fictional access with historical inference from traces."},{"word":"underdetermined","contextualMeaning":"Not conclusively settled because several interpretations fit.","whyAuthorUsedIt":"Characterises what remains uncertain about real people's motives."},{"word":"contingency","contextualMeaning":"The possibility that events could have unfolded differently.","whyAuthorUsedIt":"Counters the sense that a biography's outcome was inevitable."},{"word":"bounded field of evidence","contextualMeaning":"A limited, deliberately arranged set of clues available to readers.","whyAuthorUsedIt":"Explains why fictional minds can feel knowable."}]},
    {"day":11,"passage":"bootcamp-day-11-rc2","vocabulary":[{"word":"coordination","contextualMeaning":"Aligning people's actions so they can act together predictably.","whyAuthorUsedIt":"States the practical problem rituals can help solve."},{"word":"embodied expectations","contextualMeaning":"Rules made familiar through repeated physical practices.","whyAuthorUsedIt":"Shows how rituals turn abstract membership into action."},{"word":"signal of commitment","contextualMeaning":"An observable act suggesting willingness to follow a shared practice.","whyAuthorUsedIt":"Explains how ritual participation can build predictability."},{"word":"boundary","contextualMeaning":"A distinction between those included in a group and those outside it.","whyAuthorUsedIt":"Shows rituals can create exclusion as well as solidarity."}]},
    {"day":11,"passage":"bootcamp-day-11-rc3","vocabulary":[{"word":"ecological succession","contextualMeaning":"A sequence of changes in organisms occupying an environment over time.","whyAuthorUsedIt":"Describes the changing communities supported by a whale fall."},{"word":"organic matter","contextualMeaning":"Material from living organisms that can supply nutrients or energy.","whyAuthorUsedIt":"Identifies the resource concentrated in the carcass."},{"word":"resource partitioning","contextualMeaning":"Different organisms using distinct parts or stages of a resource.","whyAuthorUsedIt":"Explains how successive communities exploit the whale fall."},{"word":"chemical substrate","contextualMeaning":"Material that organisms use in chemical processes or as a base for growth.","whyAuthorUsedIt":"Shows how the remains support life after soft tissue is gone."}]},
    {"day":12,"passage":"bootcamp-day-12-rc1","vocabulary":[{"word":"cumulative","contextualMeaning":"Built up as earlier knowledge is retained and further developed.","whyAuthorUsedIt":"Distinguishes human cultural inheritance from isolated learning."},{"word":"repertoire","contextualMeaning":"A stored collection of practices, tools, and knowledge available to a group.","whyAuthorUsedIt":"Shows that learners begin within inherited solutions."},{"word":"reciprocal","contextualMeaning":"Mutually influencing one another over time.","whyAuthorUsedIt":"Describes the interaction between culture and biological evolution."},{"word":"autonomy","contextualMeaning":"Capacity to make and revise one's own choices.","whyAuthorUsedIt":"Argues that agency develops through cultural resources."}]},
    {"day":12,"passage":"bootcamp-day-12-rc2","vocabulary":[{"word":"instrumental value","contextualMeaning":"Worth based on usefulness for achieving human purposes.","whyAuthorUsedIt":"Names one limited basis used to justify biodiversity."},{"word":"ecological redundancy","contextualMeaning":"Some overlap in the functions performed by different organisms.","whyAuthorUsedIt":"Qualifies, without dismissing, the idea that species can substitute."},{"word":"intrinsic value","contextualMeaning":"Worth that does not depend on usefulness to people.","whyAuthorUsedIt":"Introduces ethical grounds beyond human benefit."},{"word":"valuation","contextualMeaning":"An assessment of worth, often using chosen measures or priorities.","whyAuthorUsedIt":"Shows how conservation arguments depend on what gets counted."}]},
    {"day":12,"passage":"bootcamp-day-12-rc3","vocabulary":[{"word":"ideal-typical","contextualMeaning":"A simplified analytical model used to compare real institutions.","whyAuthorUsedIt":"Clarifies how Weber's framework can explain without fully judging."},{"word":"calculability","contextualMeaning":"The ability to predict outcomes through stable procedures.","whyAuthorUsedIt":"Names bureaucracy's administrative strength."},{"word":"legibility","contextualMeaning":"The ease with which a central authority can classify and process information.","whyAuthorUsedIt":"Explains why bureaucracies rely on records and categories."},{"word":"discretion","contextualMeaning":"Judgment used when applying general rules to particular cases.","whyAuthorUsedIt":"Shows that personal interpretation remains inside formal systems."}]},
    {"day":13,"passage":"bootcamp-day-13-rc1","vocabulary":[{"word":"stopover","contextualMeaning":"A temporary site where a migrating bird rests or feeds.","whyAuthorUsedIt":"Highlights a necessary stage between endpoints of migration."},{"word":"phenology","contextualMeaning":"The timing of recurring seasonal biological events.","whyAuthorUsedIt":"Captures the food and seasonal timing that climate change can shift."},{"word":"departure window","contextualMeaning":"A limited period when conditions permit the next stage of travel.","whyAuthorUsedIt":"Shows why timing constrains migratory flexibility."},{"word":"ecological coordination","contextualMeaning":"The alignment between a species' needs and seasonal resource timing.","whyAuthorUsedIt":"Frames migration as a connected timing problem."}]},
    {"day":13,"passage":"bootcamp-day-13-rc2","vocabulary":[{"word":"plausible","contextualMeaning":"Convincing or likely on the surface, without being proven valuable.","whyAuthorUsedIt":"Distinguishes fluent output from cultural worth."},{"word":"agency","contextualMeaning":"The capacity to make choices and shape one's creative work.","whyAuthorUsedIt":"Frames how tools redistribute creative control."},{"word":"legible","contextualMeaning":"Recognisable to a system's measures or expectations.","whyAuthorUsedIt":"Explains how platforms can shape what creators produce."},{"word":"circulation","contextualMeaning":"The movement of cultural work through audiences and platforms.","whyAuthorUsedIt":"Shows that culture includes how work is encountered."}]},
    {"day":13,"passage":"bootcamp-day-13-rc3","vocabulary":[{"word":"norms","contextualMeaning":"Shared expectations about acceptable behaviour in a group.","whyAuthorUsedIt":"Explains how gossip can informally regulate conduct."},{"word":"framed","contextualMeaning":"Presented in a way that shapes how others interpret a report.","whyAuthorUsedIt":"Highlights how gossip is not neutral transmission."},{"word":"informal regulation","contextualMeaning":"Social pressure that shapes behaviour without official rules.","whyAuthorUsedIt":"Names gossip's influence outside formal institutions."},{"word":"accountability","contextualMeaning":"Being answerable for conduct and its consequences.","whyAuthorUsedIt":"Captures gossip's possible role alongside its risks of exclusion."}]},
    {"day":14,"passage":"bootcamp-day-14-rc1","vocabulary":[{"word":"salient","contextualMeaning":"Noticeable or important within the interpretation being made.","whyAuthorUsedIt":"Explains why a proposed pattern changes what people notice."},{"word":"diagnostic","contextualMeaning":"Providing evidence that distinguishes one explanation from alternatives.","whyAuthorUsedIt":"Sets a standard for evaluating a perceived regularity."},{"word":"disconfirming evidence","contextualMeaning":"Observations that count against a proposed pattern.","whyAuthorUsedIt":"Shows how a pattern can be tested rather than protected."},{"word":"calibrated","contextualMeaning":"Adjusted so judgments match the reliability of evidence or feedback.","whyAuthorUsedIt":"Explains why expertise may help only where feedback is dependable."}]},
    {"day":14,"passage":"bootcamp-day-14-rc2","vocabulary":[{"word":"economies of scale","contextualMeaning":"Lower per-unit costs achieved by producing or operating at larger volume.","whyAuthorUsedIt":"States a major advantage that does not dominate every market."},{"word":"fragmented market","contextualMeaning":"A market divided by varied local needs or customer preferences.","whyAuthorUsedIt":"Explains where small firms can compete on fit."},{"word":"bottleneck","contextualMeaning":"A constraint that limits how much work or growth is possible.","whyAuthorUsedIt":"Shows how owner dependence can undermine a small firm's agility."},{"word":"niche","contextualMeaning":"A narrower customer segment with specific needs or preferences.","whyAuthorUsedIt":"Describes a possible basis for small-firm survival."}]},
    {"day":14,"passage":"bootcamp-day-14-rc3","vocabulary":[{"word":"embouchure","contextualMeaning":"The player's shaping of lips and mouth to direct air into the flute.","whyAuthorUsedIt":"Names bodily control that affects sound and pitch."},{"word":"resonant modes","contextualMeaning":"Frequencies at which the air column naturally vibrates strongly.","whyAuthorUsedIt":"Explains how the tube shapes the flute's sound."},{"word":"end correction","contextualMeaning":"An adjustment accounting for air movement beyond a tube's physical opening.","whyAuthorUsedIt":"Shows why a real flute differs from an ideal tube model."},{"word":"partials","contextualMeaning":"Frequency components that combine to form a musical tone.","whyAuthorUsedIt":"Connects energy distribution to tone quality."}]},
    {"day":15,"passage":"bootcamp-day-15-rc1","vocabulary":[{"word":"reticence","contextualMeaning":"A reluctance to speak or disclose something.","whyAuthorUsedIt":"Offers one possible meaning a literary silence may carry."},{"word":"horizon of expectation","contextualMeaning":"What readers have been led to expect from a narrative.","whyAuthorUsedIt":"Explains why an omission becomes noticeable as a device."},{"word":"narrative access","contextualMeaning":"What a story allows readers to know and when.","whyAuthorUsedIt":"Frames silence as an arrangement of available knowledge."},{"word":"inference","contextualMeaning":"A conclusion drawn from clues rather than directly stated information.","whyAuthorUsedIt":"Describes the reader's role around an omission."}]},
    {"day":15,"passage":"bootcamp-day-15-rc2","vocabulary":[{"word":"kin selection","contextualMeaning":"Helping relatives in ways that can support shared hereditary material.","whyAuthorUsedIt":"Presents one evolutionary explanation for costly helping."},{"word":"reciprocal cooperation","contextualMeaning":"Cooperation sustained by possible return help in later interactions.","whyAuthorUsedIt":"Explains helping where partners can remember and respond."},{"word":"free-riding","contextualMeaning":"Taking cooperative benefits without contributing a share.","whyAuthorUsedIt":"Identifies a problem norms or punishment may address."},{"word":"institutional inertia","contextualMeaning":"The persistence of established institutions even when conditions change.","whyAuthorUsedIt":"Shows why a norm's persistence alone does not prove adaptive value."}]},
    {"day":15,"passage":"bootcamp-day-15-rc3","vocabulary":[{"word":"physiological preparation","contextualMeaning":"Bodily changes that ready the bird for sustained migration.","whyAuthorUsedIt":"Explains how the godwit prepares for long-distance flight."},{"word":"remodelling","contextualMeaning":"A change in bodily structure or function as conditions shift.","whyAuthorUsedIt":"Describes organ changes during the transition to flight."},{"word":"tailwinds","contextualMeaning":"Winds blowing in the direction of travel, helping forward movement.","whyAuthorUsedIt":"Shows how weather changes flight effort and timing."},{"word":"interdependent","contextualMeaning":"Mutually affecting one another rather than operating separately.","whyAuthorUsedIt":"Connects energy, timing, and weather in migration success."}]},
    {"day":16,"passage":"bootcamp-day-16-rc1","vocabulary":[{"word":"coordination","contextualMeaning":"Aligning expectations so people can act together.","whyAuthorUsedIt":"Shows advertising may help resolve shared uncertainty, not just inform."},{"word":"network effects","contextualMeaning":"A product becoming more useful as more people adopt it.","whyAuthorUsedIt":"Explains why consumers may wait for broader participation."},{"word":"adoption","contextualMeaning":"Beginning to use a product or join a practice.","whyAuthorUsedIt":"Distinguishes use from a considered judgment of merit."},{"word":"endorsement","contextualMeaning":"An explicit or considered expression of approval.","whyAuthorUsedIt":"Separates consumer approval from simply taking part."}]},
    {"day":16,"passage":"bootcamp-day-16-rc2","vocabulary":[{"word":"intermediaries","contextualMeaning":"People who facilitate exchange between places or groups.","whyAuthorUsedIt":"Shows trade routes depended on more than physical paths."},{"word":"enforcement","contextualMeaning":"Making agreements or rules reliably binding in practice.","whyAuthorUsedIt":"Explains why trust in agreements affects route viability."},{"word":"cultural diffusion","contextualMeaning":"The spread of practices or ideas between communities.","whyAuthorUsedIt":"Introduces a simplified account the passage qualifies."},{"word":"reciprocal","contextualMeaning":"Mutual in influence, though not necessarily equal.","whyAuthorUsedIt":"Qualifies how exchange can affect groups unevenly."}]},
    {"day":16,"passage":"bootcamp-day-16-rc3","vocabulary":[{"word":"register","contextualMeaning":"A level or style of language suited to a context or relationship.","whyAuthorUsedIt":"Shows how translation can shift a phrase's social force."},{"word":"fidelity","contextualMeaning":"Faithfulness to the source text's purpose and effects.","whyAuthorUsedIt":"Frames translation as reasoned choices rather than word matching."},{"word":"compensated","contextualMeaning":"Made up for elsewhere when a feature cannot be preserved directly.","whyAuthorUsedIt":"Describes how translators can manage unavoidable losses."},{"word":"ambiguity","contextualMeaning":"The possibility of more than one defensible interpretation.","whyAuthorUsedIt":"Shows how translation choices can preserve or erase uncertainty."}]}
  ]$$::jsonb;
begin
  for item in select value from jsonb_array_elements(patch)
  loop
    select document into target_document
    from public.bootcamp_days
    where id = 'bootcamp-day-' || (item->>'day');
    if target_document is null then
      raise exception 'Missing target row for day %', item->>'day';
    end if;
    if not exists (
      select 1 from jsonb_array_elements(target_document #> '{content,passages}') as p(value)
      where value->>'id' = item->>'passage'
    ) then
      raise exception 'Missing passage %', item->>'passage';
    end if;
    if target_document #> array['enrichment', item->>'passage'] is null then
      raise exception 'Missing enrichment object for %', item->>'passage';
    end if;
    if (target_document #> array['enrichment', item->>'passage']) ? 'vocabulary' then
      continue;
    end if;
    update public.bootcamp_days
      set document = jsonb_set(
        document,
        array['enrichment', item->>'passage', 'vocabulary'],
        item->'vocabulary',
        true
      )
      where id = 'bootcamp-day-' || (item->>'day')
        and not ((document #> array['enrichment', item->>'passage']) ? 'vocabulary');
    get diagnostics changed = row_count;
    if changed <> 1 then
      raise exception 'Concurrent change or unexpected target for %', item->>'passage';
    end if;
  end loop;
end;
$vocabulary_patch$;
commit;
