const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n')));
for(const [p,state,allowed,def] of [['components/RCView.jsx','rcTab',['generate','paste','profile','history'],'generate'],['components/VocabLab.jsx','tab',['bank','drill','learn','profile'],'bank'],['components/SpeedContainer.jsx','tab',['drill','profile'],'drill']])edit(p,s=>s.replace('"use client";','"use client";\nimport { useRouteTab } from "@/lib/mobile/useRouteTab";').replace(`const [${state}, set${state[0].toUpperCase()+state.slice(1)}] = useState("${def}");`,`const [${state}, set${state[0].toUpperCase()+state.slice(1)}] = useRouteTab(${JSON.stringify(allowed)},"${def}");`));
edit('components/ProfileView.jsx',s=>s.replace('import { supabase }','import Link from "next/link";\nimport { supabase }').replace('      {/* HERO SECTION */}',`      <section className="mobile-profile-links" aria-label="History and progress"><h2>History and progress</h2><Link href="/?view=workout&tab=history">Workout history</Link>{capabilities.showDailyRC&&<Link href="/rc-history">Daily RC history</Link>}{entitlement.hasAccess&&<><Link href="/?view=rc&tab=history">RC practice history</Link><Link href="/?view=vocab&tab=profile">Vocabulary progress</Link><Link href="/?view=speed&tab=profile">Speed progress</Link></>}</section>
      {/* HERO SECTION */}`));
edit('components/mobile/MobileShell.jsx',s=>s.replace('return <DailyActivityProvider>{children}{isStudent&&active&&','return <DailyActivityProvider>{isStudent&&active&&').replace('>Exit activity</button>}{isStudent&&!active','>Exit activity</button>}{children}{isStudent&&!active'));
edit('app/page.js',s=>s.replace('if (locked) {\n  router.push("/pricing")','if (locked) {\n  setLockedFeature(FEATURES.find(f=>f.id===item.id) || {id:item.id,name:item.label})'));
edit('app/daily-challenge/test/page.jsx',s=>s.replace('const [pane,setPane]=useState("passage");','const [pane,setPane]=useState("passage");\n  const paneScroll=useRef({passage:0,questions:0});\n  function changePane(next){paneScroll.current[pane]=window.scrollY;setPane(next);requestAnimationFrame(()=>window.scrollTo(0,paneScroll.current[next]));}').replaceAll("onClick={()=>setPane('passage')}","onClick={()=>changePane('passage')}").replaceAll("onClick={()=>setPane('questions')}","onClick={()=>changePane('questions')}").replace('key={index}\n                        onClick','key={index}\n                        disabled={submitting || !!savedAttemptRef.current}\n                        aria-pressed={selected}\n                        onClick'));
edit('components/WorkoutEngine.jsx',s=>s.replace('setAttemptSaved(true);return;','setAttemptSaved(true);if(!completedAnalyticsRef.current){completedAnalyticsRef.current=true;completeLearningActivity("daily_workout");}return;'));
edit('components/SpeedGym.jsx',s=>s.replace('phase === "reading" || phase === "question"','phase === "reading" || phase === "question" || saving || !!saveError'));
fs.appendFileSync('app/mobile.css','\n.mobile-profile-links{display:none}@media(max-width:899px){.mobile-profile-links{display:grid;gap:8px;margin:18px 0;padding:16px;border:1px solid #354b69;border-radius:14px}.mobile-profile-links h2{font-weight:700}.mobile-profile-links a{min-height:44px;display:flex;align-items:center;color:#b4d4ff}.assessment-exit{position:sticky;top:0;bottom:auto;right:auto;margin:0 12px 0 auto;width:fit-content;height:44px;min-height:44px;z-index:60}.daily-test-mobile-header{top:44px}.daily-test .daily-question-footer{padding-bottom:12px!important}.mobile-student-shell:has(.mobile-conversation){padding-bottom:0}}\n');
