const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n')));
edit('components/home-v2/BirbalFloatingButton.jsx',s=>s.replace('window.innerWidth < 768','window.innerWidth < 900').replace('<button\n onClick','<button aria-label="Ask Birbal"\n onClick').replace('      fixed\n      bottom-24','      birbal-launcher fixed\n      bottom-24'));
edit('app/components/MobileBottomNav.jsx',s=>s.replace('href={`/?view=${key}`} aria-current','href={`/?view=${key}`} aria-label={label} aria-current'));
edit('app/page.js',s=>s.replace('{user && view !== "home" && <div className="ml-auto">','{user && <div className="ml-auto">'));
edit('tests/inbox.test.mjs',s=>s.replace('["Home", "Practice", "CAT", "Profile"]','["Home", "Today", "Practice", "Profile"]'));
edit('tests/daily-rc-review.test.mjs',s=>s.replace('await compile("../components/DailyRCResult.jsx", {','await compile("../components/DailyRCResult.jsx", { "@/components/mobile/NextActivity": { default: () => null },'));
edit('components/RCView.jsx',s=>s.replace('import { RCReport,', 'import NextActivity from "./mobile/NextActivity";\nimport { RCReport,').replace('{phase === "result" && result && <RCReport', '{phase === "result" && result && <><NextActivity current="rc"/><RCReport').replace('continueLabel={rcMode === "plan" ? "Start Next RC" : "Generate New Passage"} />}','continueLabel={rcMode === "plan" ? "Start Next RC" : "Generate New Passage"} /></>}'));
edit('app/daily-challenge/page.jsx',s=>s.replace('import { supabase }','import Recovery from "@/components/mobile/Recovery";\nimport { fetchWithTimeout, withTimeout } from "@/lib/mobile/request";\nimport { supabase }').replace('const [activeTab,','const [error,setError]=useState(null);\n  const [retry,setRetry]=useState(0);\n  const [activeTab,').replace('    try {','    setLoading(true);setError(null);\n    try {').replace('await supabase.auth.getSession()', 'await withTimeout(supabase.auth.getSession())').replace('await fetch(', 'await fetchWithTimeout(').replace('      const data =','      if(!response.ok)throw new Error("Daily RC could not load. Please retry.");\n      const data =').replace('console.error(err);','setError(err.message);').replace('}, []);','}, [retry]);').replace('if (!challenge) {','if (error || !challenge) {').replace('Failed to load challenge','<Recovery area="daily_rc" message={error || "No challenge is available yet."} onRetry={()=>setRetry(n=>n+1)}/>'));
edit('lib/mobile/request.js',s=>s.replace('finally { clearTimeout(timer); }\n}', 'finally { clearTimeout(timer); }\n}')); // cleanup signal listener separately below
edit('lib/mobile/request.js',s=>{const i=s.lastIndexOf('finally { clearTimeout(timer); }');return s.slice(0,i)+s.slice(i).replace('finally { clearTimeout(timer); }','finally { clearTimeout(timer); options.signal?.removeEventListener("abort", abort); }');});
fs.appendFileSync('app/mobile.css','\n@media(max-width:899px){.birbal-launcher{bottom:calc(82px + env(safe-area-inset-bottom,0px))!important;right:16px!important;width:48px!important;height:48px!important;animation:none!important}.daily-test .daily-question-panel .w-10{min-width:40px}.daily-test .daily-passage-panel>div>div:first-child>div{flex-wrap:wrap;gap:8px}.daily-test-mobile-header .today-tabs{grid-template-columns:1fr 1fr}}\n');
